batteries-included/batteries-included

- platform_umbrella/apps/common_core/lib/common_core/et/ollama_report.ex
- platform_umbrella/apps/common_core/lib/common_core/et/traditional_services_report.ex
- platform_umbrella/apps/common_core/lib/common_core/et/usage_report.ex
- platform_umbrella/apps/common_core/test/common_core/et/usage_report_test.exs
- platform_umbrella/apps/common_core/test/support/factory.ex
Summary:
Add reports for Ollama and TraditionalServices
Test Plan:
`mix test`
> add: ollama and traditional services

- README.md
Summary:
We user goreleaser for building the go binary `bi`
Test Plan:
asdf install
> docs: add the needed asdf plugin

- platform_umbrella/apps/common_core/lib/common_core/accounts/admin_teams.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/router.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/user_auth.ex
Summary:
- Add a check if a user is a batteriesincl team member
- Use that check to require that users are batteriesincl for /admin
Test Plan:
visited before adding myself, got a redirect
visited after got there.
> fix: correctly require batteries inlcluded team for /admin

- platform_umbrella/apps/common_core/lib/common_core/batteries/victoria_metrics_config.ex
- platform_umbrella/apps/common_core/lib/common_core/batteries/vm_agent_config.ex
- platform_umbrella/apps/common_ui/lib/common_ui/components/input.ex
- platform_umbrella/apps/common_ui/lib/common_ui/helpers/text_helpers.ex
- platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/input_test/test_disabled_password_component.heyya_snap
- platform_umbrella/apps/common_ui/test/common_ui/components/input_test.exs
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/batteries/battery_core_form.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/batteries/forgejo_form.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/batteries/grafana_form.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/batteries/keycloak_form.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/batteries/knative_form.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/batteries/notebooks_form.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/batteries/smtp4dev_form.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/batteries/victoria_metrics_form.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/batteries/vm_agent_form.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/notebooks/form_component.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/postgres/form_component.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/postgres/postgres_form_subcomponents.ex
- platform_umbrella/apps/control_server_web/test/live/postgres_live_test.exs
Summary:
- For passwords we don't want to send them to the user at all after they
are created. So this adds a new input for disabled passwords that uses
the obfusacte method.
- Add some read only fields tags for secret values.
-
Test Plan:
- Test added for input with disabled password.
> feat: UI changes for read only fields

- platform_umbrella/apps/common_core/lib/common_core/containers/container.ex
- platform_umbrella/apps/common_core/lib/common_core/ecto/schema.ex
- platform_umbrella/apps/common_ui/lib/common_ui/components/input_list.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/containers/container_modal.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/containers/containers_panel.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/containers/hidden_forms.ex
Addresses #425 by replacing the `command` field in the container form with a virtual `path` field, and adds an input list for container arguments.
> Support path and arguments for containers

- platform_umbrella/apps/home_base_web/config/runtime.exs
- platform_umbrella/config/config.exs
Summary:
Set up swoosh to use the correct finch pool
Set up swoosh to use postmark for home base web prod
Set up a black hole server for home base
Test Plan:
Get a prod server up and running again.
> feat: use postmark to deliver on prod

- platform_umbrella/apps/common_core/lib/common_core/jwk/jwk.ex
- platform_umbrella/apps/home_base/lib/home_base/customer_installs.ex
- platform_umbrella/apps/home_base_web/config/runtime.exs
- platform_umbrella/apps/home_base_web/lib/home_base_web/controllers/install_spec_controller.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/controllers/stored_host_report_controller.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/controllers/stored_usage_report_controller.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/live/installation/show_live.ex
- platform_umbrella/apps/home_base_web/test/home_base_web/controllers/jwk_delete_test.exs
Summary:
For every install we generate a curve pair. Home base will verify all
messages for usage and hosts with that key. We don't want others to get
it. So this makes the first report to remove the key.
This also adds some palces where we assert that the keys are using our
curve. That's becuase I made assumptions about how the keys are
structured based upon this key type.
Test Plan:
- Tests Added
> security: remove all traces of the private key as early as possible

- platform_umbrella/apps/common_core/priv/keys/.gitignore
I think, by preventing all files in the keys directory and explicitly allowing specific public keys, we're less likely to accidently commit something?
> chore: switch to key allowlist

- platform_umbrella/apps/home_base_web/lib/home_base_web/live/installation/show_live.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/request_host.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/router.ex
Summary:
When coming to home base, we can have a lot of hostnames. So figure that
out at run time. However live view doesn't really offer that since the
socket persists. Instead we use the last on we saw before leaving
Plug.Conn goodbye.
Test Plan:
```
/bin/bash -c "$(curl -fsSL http://home.127-0-0-1.batrsinc.co:4100/installations/batt_01922808981a728a95959a2488018987/script)"
```
> feat: use the current request host, port, and scheme for starting

- platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
- platform_umbrella/apps/common_core/lib/common_core/et/stable_versions_report.ex
Summary:
0.19.0 should include enough that the script can work. So start using
it.
Test Plan:
Deploy a new home base and try it out.
> chore: bump the stable bi version now that 0.19.0 has been released

- platform_umbrella/apps/control_server_web/lib/control_server_web/plug/api_sso_auth.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/router.ex
- platform_umbrella/apps/kube_services/lib/kube_services/keycloak/user_client.ex
Summary:
For now this isn't very performant, but we check that the api has a
valid token by fetching the userinfo.
Test Plan:
```
curl -X GET -H "Authorization: Bearer $token" http://control.127-0-0-1.batrsinc.co:4000/api/postgres/clusters | jq
```
Adding chars to the token fails everything.
Not passing a token fails everything.
> feat: secure the api

- bi/pkg/specs/get_spec.go
Summary:
Localhost has a different hostname for most of our home base dev
installs
Test Plan:
Locally
> fix: download from home on 127-0-0-1.batrsinc.co

- platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Summary:
0.20.0 bi has fixes that should make it work on localhost even with
different hostnames.
Test Plan:
bix bootstrap
> chore: update bi to 0.20.0

- platform_umbrella/apps/control_server_web/lib/control_server_web/components/projects/ai_form.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/projects/database_form.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/projects/web_form.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/projects/new.ex
This addresses #469 by creating individual pg users for each service created under a new project. An initial `root` user is created with superuser permissions (but not attached to anything), then `jupyter`, `knative`, and `traditional` users are created with login permissions depending on the project type, and attached to the service.
- Allow database name to be edited for new projects
> Add individual postgres users for project resources

- platform_umbrella/apps/kube_services/lib/kube_services/keycloak/wellknown_client.ex
- platform_umbrella/apps/kube_services/lib/kube_services/system_state/keycloak_summarizer.ex
- platform_umbrella/apps/kube_services/lib/kube_services/system_state/summarizer.ex
- platform_umbrella/config/config.exs
Summary:
When the oauth server is up, but not responding Summarizer was crashing. That's because the timeouts were all out of wack. So this adds a timeout to everything.
Test:
Ran it on my mac with vpn down and it times out.
> feat: add timeouts and logging to the oauth flow

- platform_umbrella/apps/home_base/lib/home_base/customer_installs.ex
- platform_umbrella/apps/home_base/test/home_base/customer_installs_test.exs
- platform_umbrella/apps/home_base_web/lib/home_base_web/live/dashboard_live.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/live/installation/index_live.ex
Addresses #884 by adding two new panels to replace the checklist for starting an installation/creating a team, a panel for recent installations across all teams (which will automatically switch to the team if clicked), and a total team count. Also changed the total installation count to include installations across all of the user's teams, and removed the placeholder graphs.
---
> Home base dashboard updates

- pastebin-go/main.go
Summary:
This follow knative usage of it. The default is 8080 which is why this
worked on there.
Test Plan:
Deploy
> feat: allow example pastebin to use the env PORT for http port

- platform_umbrella/apps/common_core/lib/common_core/resources/monitoring/vm_agent.ex
The removed configuration relabels all metrics with `cluster="cluster-name"`. cnpg labels all of their metrics with the cnpg cluster name and the dashboards rely on it but it was getting overwritten. Remove the relabeling.
> fix(monitoring): get cloudnative pg dashboards working

- platform_umbrella/apps/common_ui/lib/common_ui/components/script.ex
- platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/script_test/test_script_with_custom_link.heyya_snap
- platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/script_test/test_script_with_template_component.heyya_snap
- platform_umbrella/apps/common_ui/test/common_ui/components/script_test.exs
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/keycloak/new_user_form.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/keycloak/users_table.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/keycloak/realm.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/keycloak/realms_list.ex
- platform_umbrella/apps/control_server_web/test/__snapshots__/components/keycloak/tables_test/test_keycloak_users_table__1_with_a_user.heyya_snap
- platform_umbrella/apps/kube_services/lib/kube_services/keycloak/user_manager.ex
This fixes #890 by implementing a better UI for creating new and editing existing keycloak users.
- Replaces the "Reset Password"/"Make Realm Admin" links in the table with an "Edit User" modal containing buttons for the same options
- Styles the temporary password modal with a copy to clipboard button and a link to the keycloak instance
- Automatically generates a temporary password after creating the user
- Adds a switch for making the new user an admin during creation
- Fixes a crash when trying to view all realms and there are none
- Properly displays errors coming from the keycloak API
- Adds global flash messages for errors
---
> Better UI for adding and editing keycloak users

- platform_umbrella/apps/common_ui/lib/common_ui/components/email.ex
- platform_umbrella/apps/common_ui/lib/common_ui/helpers/email_helpers.ex
- platform_umbrella/apps/common_ui/test/common_ui/helpers/email_helpers_test.exs
- platform_umbrella/apps/home_base_web/lib/home_base_web.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/emails/welcome_confirm_email.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/live/forgot_password_live.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/live/installation/show_live.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/live/settings_live.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/live/signup_live.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/live/teams/new_live.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/request_host.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/router.ex
- platform_umbrella/apps/home_base_web/test/home_base_web/emails/welcome_confirm_email_test.exs
- platform_umbrella/config/config.exs
- platform_umbrella/config/prod.exs
Fixes https://github.com/batteries-included/batteries-included/issues/1018 by using the request scheme and authority for constructing URLs in emails. Also renames the `home_url` config value to `marketing_url` as to not confuse it with the home base url.
Related to https://github.com/batteries-included/batteries-included/issues/1013
> Use current host for constructing email URLs

- platform_umbrella/apps/common_core/lib/common_core/et/urls.ex
- platform_umbrella/apps/kube_services/lib/kube_services/et/usage.ex
Summary:
This has two main parts
- Don't assert that sending a usage report always works. This should
stop the GenServer from crashing. InstallStatus will still time out
and everythin will crash after a while if this is isn't correct.
AKA this fixes #1029
- Change the prod url to a hostname the points to prod home base.
AKA this fixes #1028
Test Plan:
- Test with latest when possible.
- Code review carefuly please
> fix: don't crash with nxdomain on ET.HomeBaseClient for prod

- platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Summary:
Preparing for launch marking the latest and greatest bi as stable for
use in the install script
Test Plan:
- Tested with 0.24.0
> chore: update bi stable version

- platform_umbrella/apps/common_core/lib/common_core/et/urls.ex
- static/src/components/widgets/Header.astro
- static/src/components/widgets/StartBuild.astro
- static/src/content/post/open-source-payoff.md
- static/src/content/post/public-beta-announcement.md
- static/src/data/navigation.ts
- static/src/pages/landing/deploy-at-the-speed-of-users.astro
- static/src/pages/landing/deploy-your-cloud-in-seconds.astro
- static/src/pages/landing/enable-your-devops-team-to-move-mountains.astro
- static/src/pages/solutions/ai.astro
- static/src/pages/solutions/database.astro
- static/src/pages/solutions/security.astro
- static/src/pages/solutions/sre_tools.astro
- static/src/pages/solutions/web-deploy.astro
Summary:
Our internal prod has a cname. We should use that now that JTarasovic
has pulled the rabbit out of the hat, and gotten us dns names for
traditional services
Test Plan:
- CI
- Click on netlify
> docs: switch to the new/better dns name for homebase in prod

- platform_umbrella/apps/control_server_web/lib/control_server_web/components/knative/form_component.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/notebooks/form_component.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/traditional_services/form_component.ex
This temporarily fixes the issue of not being able to delete the last item for Knative containers/env values, Traditional Service containers/env values, and Jupyter notebook env values. This is a workaround until we have a more elegant solution by submitting a PR to Ecto for supporting `drop_param` when casting array fields, and/or delving deeper into the `InputList` component and how can work with the hidden input fields.
Related to https://github.com/batteries-included/batteries-included/issues/904
> Allow empty lists for containers and env values

- platform_umbrella/apps/home_base_web/lib/home_base_web/live/installation/new_live.ex
- platform_umbrella/apps/home_base_web/priv/markdown/install/aws.md
Summary:
Dockers's the easiest way to test
Aws needs some things to work
Test Plan:
- Deploy after this builds
> docs: more new install documentation

- platform_umbrella/apps/common_ui/lib/common_ui.ex
- platform_umbrella/apps/common_ui/lib/common_ui/components/field.ex
- platform_umbrella/apps/common_ui/lib/common_ui/components/fieldset.ex
- platform_umbrella/apps/common_ui/storybook/components/field.story.exs
- platform_umbrella/apps/common_ui/storybook/components/fieldset.story.exs
- platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/field_test/test_beside_field_component.heyya_snap
- platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/field_test/test_field_component_with_note_and_help_text.heyya_snap
- platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/field_test/test_stacked_field_component.heyya_snap
- platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/fieldset_test/test_default_fieldset_component.heyya_snap
- platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/fieldset_test/test_responsive_fieldset_component.heyya_snap
- platform_umbrella/apps/common_ui/test/common_ui/components/field_test.exs
- platform_umbrella/apps/common_ui/test/common_ui/components/fieldset_test.exs
This gets started on https://github.com/batteries-included/batteries-included/issues/23 by adding `Field` and `Fieldset` components. This will help slim down the `Input` component by separating the input styling from the surrounding container and form styling.
---
> Add Field and Fieldset components

- .github/workflows/bix_docker.yml
We can tag a commit at any point. Meaning that there could be more recent commits so we shouldn't tag the released image as "latest". This accomplishes that by determining which tag to use and then only running `push-images` once with the tags that it should use as opposed to running once with latest and once with the current tag.
> ci: don't push latest image on tagging/release

- platform_umbrella/apps/common_core/lib/common_core/resources/battery/control_server.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/controllers/healthz_controller.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/router.ex
Summary:
- Checks that there are some kube state pods
- Checks that sql is up
- Add that as a liveness and readiness probe
Tests:
- `curl -vvv http://control.127-0-0-1.batrsinc.co:4000/healthz`
- Saw that fail with no pods when startin up
- Passes after 1 second
- Once this is in master and an image is built I'll bix start local
> feat: add a healthz controller

- platform_umbrella/apps/common_ui/lib/common_ui/components/input.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/postgres/form_component.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/postgres/postgres_form_subcomponents.ex
- Replaces old Input component with Field component in Postgres forms
- Restructures the panels so instance count is in its own panel
- Removes `label_note` attribute that is no longer used
Related to https://github.com/batteries-included/batteries-included/issues/23
---
> Use Field component in Postgres forms

- platform_umbrella/apps/common_core/lib/common_core/resources/battery/control_server.ex
- platform_umbrella/apps/kube_bootstrap/lib/kube_bootstrap/kube.ex
Summary:
They aren't bootstrapping, but we swallow the error. So add that to logs
Change liveness and readiness to be only on main conatiner for control
server
Test Plan:
After master has built test again /shrug
> fix: try and fix liveness/readiness probe not bootstrapping

- platform_umbrella/apps/common_core/lib/common_core/version.ex
- platform_umbrella/apps/common_core/test/common_core/version_test.exs
Trying to use an override version runs into issues when comparing version. This fixes it.
> fix: don't crash on incomparable versions

- platform_umbrella/apps/control_server_web/lib/control_server_web/controllers/healthz_controller.ex
Summary:
Healthz wasn't working
Test Plan:
`curl -vvv http://control.127-0-0-1.batrsinc.co:4000/healthz`
> fix: don't crash logging success

- platform_umbrella/apps/common_core/lib/common_core/resources/monitoring/vm_cluster.ex
related to: #1176 
Unitless number is interpreted as months. Change to days.
> fix(monitoring): change vm storage retention from months to days

- .github/workflows/bix.yml
- .github/workflows/bix_docker.yml
- .github/workflows/bix_elixir.yml
- .github/workflows/bix_go.yml
- .github/workflows/release.yml
The caches are getting a bit big because we just keep adding new versions to them. For asdf, it seems like we could just take the cache miss when we are updating tools and we'll get a completely fresh cache. Since we generally update multiple at once and the tools don't take _too_ long to install, I think it's a pretty good tradeoff but am not super tied to it if you disagree.
> ci: clean asdf cache on changes

- platform_umbrella/apps/control_server/lib/control_server/release.ex
I already fixed this in `home_base` but must have missed it here in `control_server`. Noticed that it was giving a warning during bootstrap as we were troubleshooting the password issue just now.
> chore(control): fix bootstrap warning

- platform_umbrella/apps/common_core/lib/common_core/keycloak/admin_client.ex
- platform_umbrella/apps/common_core/lib/common_core/open_api/keycloak_admin_schema.ex
- platform_umbrella/apps/common_core/mix.exs
- platform_umbrella/apps/common_core/test/common_core/keycloak/admin_client_test.exs
- platform_umbrella/apps/common_ui/mix.exs
- platform_umbrella/apps/control_server/mix.exs
- platform_umbrella/apps/control_server_web/mix.exs
- platform_umbrella/apps/event_center/mix.exs
- platform_umbrella/apps/home_base/mix.exs
- platform_umbrella/apps/home_base_web/mix.exs
- platform_umbrella/apps/kube_bootstrap/mix.exs
- platform_umbrella/apps/kube_services/lib/kube_services/keycloak/admin_client.ex
- platform_umbrella/apps/kube_services/lib/kube_services/system_state/keycloak_summarizer.ex
- platform_umbrella/apps/kube_services/mix.exs
The forms and actions methods needed to be moved to `KubeServices` for ease of getting the fields into the state summary. This is the next step in getting TOTP enabled for keycloak programatically.
> feat(keycloak): add forms and actions to state summary

- platform_umbrella/apps/common_core/lib/common_core/actions/sso.ex
- platform_umbrella/apps/common_core/lib/common_core/batteries/sso_config.ex
- platform_umbrella/apps/common_core/lib/common_core/state_summary/keycloak_summary.ex
- platform_umbrella/apps/control_server/lib/control_server/snapshot_apply/keycloak_action.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/batteries/sso_form.ex
- platform_umbrella/apps/event_center/lib/event_center/keycloak.ex
- platform_umbrella/apps/kube_services/lib/kube_services/snapshot_apply/apply_action.ex
Allows turning on MFA for `batterycore` realm.
Test plan:
> feat(sso): allow requiring MFA

- platform_umbrella/apps/control_server_web/test/controllers/cluster_controller_test.exs
Summary:
Sometimes the factory was chosing ok sizes, sometimes it failed. This
changes to always use the same size tiny in the test
Test Plan:
- Tests pass
> test: fix cluster controller test flakiness

- .github/dependabot.yml
Summary:
When we build js we don't really have a production vs development split.
We only care about the end result in the image so put all the js into a
single group.
Test Plan:
- CI
> refactor: use a single dependency group where needed

- static/src/pages/index.astro
- static/src/pages/solutions/web-deploy.astro
Summary:
We have a couple of new videos to demo our flow. Since they are up we
should use them on the website. This PR updates the web and index pages
to use the new embed code
Test Plan:
- Tested locally
- netlify
- verify that deploy preview embeds the new vides for both pages
> docs: use new youtube embed links for web and main flow

- static/src/pages/solutions/web-deploy.astro
Summary:
There's an emebd there too that I didn't see
Test Plan:
CI clean
> fix: change the embed url in we deploy as well.

- platform_umbrella/apps/common_core/lib/common_core/batteries/victoria_metrics_config.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/batteries/victoria_metrics_form.ex
part of: #1176 
This doesn't use sliders yet. Just preset sizes.
> feat(monitoring): use preset sizes for victoria metrics

- platform_umbrella/apps/common_ui/lib/common_ui/components/button.ex
- platform_umbrella/apps/common_ui/lib/common_ui/components/markdown.ex
```
warning: Passing the tag name to `Phoenix.Component.dynamic_tag/1` using the `name` attribute is deprecated.
Instead of:
<.dynamic_tag name="p" ...>
use `tag_name` instead:
<.dynamic_tag tag_name="p" ...>
```
```
grep -R dynamic_tag platform_umbrella/apps
platform_umbrella/apps/common_ui/lib/common_ui/components/button.ex:    <.dynamic_tag tag_name={@tag} class={[button_class(assigns[:variant]), @class]} {@rest}>
platform_umbrella/apps/common_ui/lib/common_ui/components/button.ex:    </.dynamic_tag>
platform_umbrella/apps/common_ui/lib/common_ui/components/markdown.ex:    <.dynamic_tag tag_name={@tag} class={["prose dark:prose-invert", @class]} {@rest}>
platform_umbrella/apps/common_ui/lib/common_ui/components/markdown.ex:    </.dynamic_tag>
```
> fix(ui): update deprecated attribute to silence warnings

- platform_umbrella/apps/common_core/lib/common_core/resources/postgres/cloudnative_pg.ex
Summary:
The default is not useful at all
Test Plan:
bix bootstrap && bix dev
- It all comes up
- The logs are there and more featureful
> feat: enable more logging for cloudnative pg

- platform_umbrella/apps/common_core/lib/common_core/resources/postgres/cloudnative_pg.ex
- platform_umbrella/apps/common_core/priv/manifests/cloudnative_pg/clusters_postgresql_cnpg_io.yaml
- platform_umbrella/apps/common_core/priv/manifests/cloudnative_pg/poolers_postgresql_cnpg_io.yaml
- platform_umbrella/apps/common_core/priv/manifests/cloudnative_pg/scheduledbackups_postgresql_cnpg_io.yaml
- platform_umbrella/apps/common_core/priv/raw_files/cloudnative_pg/queries
Summary:
- Regenerate the resource module
- Use the new monitoring queries
- Use the newest CRD's
- Update the cluster role to allow more perms and the new names
Test Plan:
- bix bootstrap && bix dev
- CI
> fix: update the cloud native pg cluster role

- bin/bix
- platform_umbrella/apps/common_core/mix.exs
- platform_umbrella/apps/common_ui/mix.exs
- platform_umbrella/apps/control_server/mix.exs
- platform_umbrella/apps/control_server_web/mix.exs
- platform_umbrella/apps/event_center/mix.exs
- platform_umbrella/apps/home_base/mix.exs
- platform_umbrella/apps/home_base_web/mix.exs
- platform_umbrella/apps/kube_bootstrap/mix.exs
- platform_umbrella/apps/kube_services/mix.exs
- platform_umbrella/apps/verify/mix.exs
- platform_umbrella/mix.exs
Summary:
Bump version
Release so that the 0.42.0 release can be used to bring up home base.
Test Plan:
- CI
> chore: prepare for 0.43.0

- .tool-versions
- bi/pkg/cluster/kind/kind.go
- bi/pkg/cluster/pulumi.go
Summary:
v1.32.0 is the latest stable release hot off the presses, or atleast
that is what the banner in aws will not stop telling me.
Test Plan:
CI
bix bootstrap
> chore: update to latest released kind node and aws kube

- bi/pkg/cluster/kind/kind.go
- bi/pkg/cluster/pulumi.go
1.32 isn't available in EKS yet (at least for new clusters).
`InvalidParameterException: unsupported Kubernetes version 1.32`
> fix: roll back k8s version update

- platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Summary:
- Use the new bi with the aws fix
Test Plan:
- Land after #1364 is in master and there's a release.
> chore: use the latest released bi

- bin/bix
- platform_umbrella/apps/common_core/mix.exs
- platform_umbrella/apps/common_ui/mix.exs
- platform_umbrella/apps/control_server/mix.exs
- platform_umbrella/apps/control_server_web/mix.exs
- platform_umbrella/apps/event_center/mix.exs
- platform_umbrella/apps/home_base/mix.exs
- platform_umbrella/apps/home_base_web/mix.exs
- platform_umbrella/apps/kube_bootstrap/mix.exs
- platform_umbrella/apps/kube_services/mix.exs
- platform_umbrella/apps/verify/mix.exs
- platform_umbrella/mix.exs
Summary:
- The plan is to release 0.44.0 as a home that can be used to start aws
installs. int-prod being what I care about the most.
- `bix set-version 0.45.0`
Test Plan:
- CI
> chore: prepare 0.45.0

- platform_umbrella/apps/control_server_web/lib/control_server_web/live/k8/resources_list.ex
Summary:
We needed to inspect a lot of things that weren't on the kube pages. So
this is re-arranging the page in order for us to start putting more data
on here
Test Plan:
- CI
- Visual
> style: restyle to kube pages to prepare for more

- platform_umbrella/apps/control_server_web/lib/control_server_web/live/ferrretdb/show.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/group_batteries/index.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/homes/data.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/homes/devtools.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/homes/magic.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/homes/monitoring.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/homes/net_sec.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/k8/deployment/show.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/k8/pod/show.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/k8/raw_resource.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/k8/resources_list.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/k8/service/show.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/k8/stateful_set/show.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/keycloak/realm.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/knative/show.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/postgres/show.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/redis/show.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/state_summary.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/timeline.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/trivy_reports/index.ex
Summary:
On the dead view render there's no need to subscribe. That won't get
updated. On re-connect we will then subscribe.
Test Plan:
- Noticed that pods still change
> perf: don't subscribe to pubsub on deadview

- platform_umbrella/apps/control_server_web/lib/control_server_web/live/k8/pod/show.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/router.ex
Summary:
- Trying things out to get a more workable show page template for other
kube based things.
- Separate the labels and annotations pages
Test Plan:
- Visual
- CI
> style: use tab_bar more for navigation

- platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Summary:
Use the latest golang bi binary
Test Plan:
CI
> chore: bump stable bi version

- static/src/components/common/BasicScripts.astro
Summary:
This errors out all the time since we don't have a left menu
Test Plan:
The browser stops yelling at me.
> fix: remove un-used btn menu code

- static/src/components/common/BasicScripts.astro
Summary:
- I removed the btn code, but it was still used for mobile. So this
reverts it.
- However it was not playing well with window.onload
- Also some pages might not have the menu, so this makes that not crash
the scripts
Test:
- Tried locally on mobile
- CI
> fix: bring back and fix the toggle btn for menu

- bin/bix
- platform_umbrella/apps/common_core/mix.exs
- platform_umbrella/apps/common_ui/mix.exs
- platform_umbrella/apps/control_server/mix.exs
- platform_umbrella/apps/control_server_web/mix.exs
- platform_umbrella/apps/event_center/mix.exs
- platform_umbrella/apps/home_base/mix.exs
- platform_umbrella/apps/home_base_web/mix.exs
- platform_umbrella/apps/kube_bootstrap/mix.exs
- platform_umbrella/apps/kube_services/mix.exs
- platform_umbrella/apps/verify/mix.exs
- platform_umbrella/mix.exs
Bump the version
I'll create a release after this lands
Tests:
CI there's no human code changes.
> chore: prepare 0.49.0 for development

- platform_umbrella/apps/common_core/lib/common_core/batteries/catalog.ex
- platform_umbrella/apps/common_core/lib/common_core/batteries/catalog_battery.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/projects/batteries_form.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/group_batteries/index.ex
- platform_umbrella/apps/control_server_web/test/components/projects/batteries_form_test.exs
- platform_umbrella/apps/control_server_web/test/live/group_batteries/index_test.exs
- platform_umbrella/apps/control_server_web/test/live/project_live_test.exs
- platform_umbrella/apps/kube_services/lib/kube_services/system_state/summary_batteries.ex
This filters out batteries from the UI if the install's usage isn't allowed. This is a form of course grained feature flagging so that we can work on features without them being generally available.
Does not currently restrict battery from being installed just removes it from the UI. We could always add that if needed.
Are there any other places where we should filter / hide these batteries?
> feat: add ability to restrict batteries by usage

- platform_umbrella/apps/common_core/lib/common_core/projects/project.ex
- platform_umbrella/apps/common_core/test/common_core/projects/project_test.exs
- platform_umbrella/apps/common_core/test/support/factory.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/projects/show.ex
I tried to add the export button on the index pages as well but was running into a bunch of issues. This just adds the simplest export functionality (without any filtering) and makes it accessible through the UI if the feature is enabled.
> feat(project): add initial export functionality to UI

- static/src/pages/docs/[...page].astro
- static/src/utils/docs.ts
Summary:
As we add more docs we want the getting started to be first so lets
codify that now. With that there are usually empty getting started
sections on non starting pages. So hide those
Test Plan:
- Netlify
- Visual
> docs: sort docs categories and hide un-used sections

- platform_umbrella/apps/common_core/lib/common_core/defaults/images.ex
- platform_umbrella/apps/control_server/lib/control_server/ollama.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/ollama/form_component.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/ollama/form_subcomponents.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/projects/ai_form.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/projects/batteries_form.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/ollama/edit.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/ollama/new.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/projects/new.ex
Summary:
- Split the ModelInstance forms into sub forms usable in project flow
- Add the model instance form to the AI project steps.
Test Plan:
> feat: allow starting an ollama model in AI projects

- platform_umbrella/apps/common_ui/lib/common_ui/components/data_list.ex
- platform_umbrella/apps/common_ui/storybook/components/data_list.story.exs
- platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/data_list_test/test_default_datalist_with_help.heyya_snap
- platform_umbrella/apps/common_ui/test/common_ui/components/data_list_test.exs
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/postgres/show.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/router.ex
- platform_umbrella/apps/control_server_web/test/live/postgres/postgres_live_test.exs
Summary:
- Use the right side nav style from kubernetes page
- Add events page
- Add a pods page
- Add an internal/standard type. Closing #461
Test Plan:
- Test added
- Tests updated
> refactor: restructur the postgres show page to allow more subpages

- platform_umbrella/apps/common_core/lib/common_core/batteries/catalog.ex
Summary:
- Hide it for now
Test Plan:
- Everything still passes
> refactor: set SMTP4Dev as internal only to deprecate

- platform_umbrella/apps/common_core/lib/common_core/resources/knative/services.ex
- platform_umbrella/apps/common_core/lib/common_core/resources/traditional_services/traditional_services.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/containers/env_value_panel.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/k8/conditions_display.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/knative/knative_services_table.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/traditional_services/traditional_services_table.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/knative/show.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/postgres/show.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/traditional_services/show.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/router.ex
Summary:
- Split the menu as before
- Add events and pods to the traditional services page
- Add events, pods, and deployments to the knative page
- add edit versions
Test Plan:
- Visual
> refactor: restructure the traditional services and knative show pages

- bi/pkg/cluster/kind/kind.go
- bi/pkg/cluster/pulumi.go
Cluster spun up and I was able to access UI.
> chore: upgrade to k8s 1.32

- .github/workflows/bix_docker.yml
Summary:
When releasing a version we push that. However there's already a latest
tag somewhere else. So we shouldn't make that tag regress.
This should fix: #1543
Test Plan:
-  CI ?
> fix: don't push latest tag on tag releases

- .github/workflows/release.yml
- .goreleaser.yaml
- .tool-versions
Summary:
Releases were missing changelogs because GitHub does a shallow clone by default.
Test Plan:
- New release
> fix: checkout release with history for changelog

- bin/bix
- platform_umbrella/apps/common_core/mix.exs
- platform_umbrella/apps/common_ui/mix.exs
- platform_umbrella/apps/control_server/mix.exs
- platform_umbrella/apps/control_server_web/mix.exs
- platform_umbrella/apps/event_center/mix.exs
- platform_umbrella/apps/home_base/mix.exs
- platform_umbrella/apps/home_base_web/mix.exs
- platform_umbrella/apps/kube_bootstrap/mix.exs
- platform_umbrella/apps/kube_services/mix.exs
- platform_umbrella/apps/verify/mix.exs
- platform_umbrella/mix.exs
Summary:
- We should have changelogs.
- Releasing 0.51.0 should exactly follow the doc
Test Plan:
- CI
> chore: prepare for 0.52.0

- .github/workflows/release.yml
- .goreleaser.yaml
- bin/clean-tmp
Summary:
- UPX makes binary size go from 99MB to 17MB
- Make the release notes have sub groups
Test Plan:
- goreleaser build --snapshot --clean
> build: use upx and group changelog

- platform_umbrella/apps/common_core/lib/common_core/ollama/model_instance.ex
- platform_umbrella/apps/common_core/lib/common_core/resources/ml/ollama.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/ollama/model_instances_table.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/ollama/show.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/router.ex
- platform_umbrella/config/config.exs
Summary:
- Change the show page UI
- Add model instances to edit versions
- update the recomended models
Test Plan:
- Visual
- Tried deepseek-r1:1.5b
> feat: allow using deepseek r1 as a model in ollama

- platform_umbrella/apps/home_base_web/priv/raw_files/install_script.sh
Summary:
TRACE means debug logging everywhere else. This makes that hold for the
install script
Fixes: #1351
Test Plan:
- CI
> feat: allow setting TRACE for install script

- bi/pkg/cluster/kind/kind.go
- bi/pkg/cluster/pulumi.go
> chore(k8s): upgrade to 1.32

- bin/bix
Quick fix for something I ran across this morning.
> fix(bix): always bootstrap against the desired cluster

- bin/bix
- platform_umbrella/apps/common_core/mix.exs
- platform_umbrella/apps/common_ui/mix.exs
- platform_umbrella/apps/control_server/mix.exs
- platform_umbrella/apps/control_server_web/mix.exs
- platform_umbrella/apps/event_center/mix.exs
- platform_umbrella/apps/home_base/mix.exs
- platform_umbrella/apps/home_base_web/mix.exs
- platform_umbrella/apps/kube_bootstrap/mix.exs
- platform_umbrella/apps/kube_services/mix.exs
- platform_umbrella/apps/verify/mix.exs
- platform_umbrella/mix.exs
Summary:
- Version bump to release 1.32 Kube
Test Plan:
- CI
- Release
> chore: prepare for 0.56.0

- static/package-lock.json
- static/src/assets/styles/tailwind.css
Summary:
New version of prettier changes css layouts. So update and include the
fix
Test Plan:
CI, and the dependabot pr closes.
> chore: update npm deps and format /static

- static/src/content/post/context-ui-for-stability.md
Summary:
This was something that I saw repeat itself over and over again at FB,
for both the database teams and the Ads/Site Integrity teams. So since
our platform is all about putting as much context in
Test Plan:
Netlify
> docs: add post about contextual information in platforms

- platform_umbrella/.credo.exs
- platform_umbrella/apps/control_server/lib/control_server/projects/snapshotter.ex
- platform_umbrella/apps/control_server/test/control_server/projects/project_snapshot_test.exs
Summary:
This PR does most of the work to allow applying a snapshot onto an
existing project.
- Rename to `Snapshotter`
- Read all the resources by name in a transaction
- Then insert the ones that aren't there
- Then update the ones that are there
This doesn't include the needed code to over-ride the virtual_size for
all resources but it's ready
Test Plan:
Tests included
bix ex-lint clean
> feat: add the ability to apply a snapshot to a project

- platform_umbrella/apps/control_server/test/control_server/postgres_test.exs
- platform_umbrella/apps/control_server/test/control_server/redis_test.exs
closes: #1421 
This changes the list_cluster pagination test to ignore clusters that may have been created in other tests or via backgound installer. This should keep it from being flakey.
> fix(control_server): de-flake list_cluster test

- .github/workflows/bix.yml
- .github/workflows/bix_docker.yml
- .github/workflows/bix_elixir.yml
- .github/workflows/bix_go.yml
- .github/workflows/release.yml
This gets rid of the warning spam about upgrade to 0.16.x. The actions don't currently support it so pin 1 version back and we can upgrade again once the actions are ready.
> ci: upgrade asdf and pin version

- bootstrap/dev.install.json
- bootstrap/dev.spec.json
- bootstrap/int-prod.install.json
- bootstrap/int-prod.spec.json
- bootstrap/int-test.install.json
- bootstrap/int-test.spec.json
- bootstrap/jason.install.json
- bootstrap/jason.spec.json
- bootstrap/local.install.json
- bootstrap/local.spec.json
- bootstrap/team.json
- platform_umbrella/apps/common_core/lib/common_core/batteries/karpenter_config.ex
- platform_umbrella/apps/common_core/lib/common_core/resources/karpenter_pools.ex
The AL2 AMIs don't have default support for GPUs but the bottlerocket AMIs do. So create a nodeclass for it and use that class for the nvidia node pool.
> chore(karpenter): enable gpu support for nvidia nodes

- platform_umbrella/apps/common_core/lib/common_core/resources/karpenter_pools.ex
I noticed that the aws-load-balancer-controller was having issues retrieving data from the metadata service when it was running on karpenter nodes. They initially run on bootstrap nodes which allow the containers to retrieve metadata.
> fix(karpenter): match instance metadata options to bootstrap values

- .github/workflows/bix.yml
- .github/workflows/bix_docker.yml
- .github/workflows/bix_elixir.yml
- .github/workflows/bix_go.yml
- .github/workflows/release.yml
Summary:
- Stop allowing the ssh key from checkout to persist
- Use fewer permissions by default
- Sanitize ref_name before putting it into an env variable
- Turn off a lot of caching for
Test Plan:
- CI
> build: improve GH action security

- platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Summary:
This will mean that we have to wait for the bi binary to build before
being able to test.
However this is needed since the keys are going to be changing.
Test Plan:
- /shrug
> chore: set the bi stable version to the next release version

- platform_umbrella/apps/common_core/lib/common_core/ollama/model_instance.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/ollama/form_component.ex
If you choose a model that's bigger than the preset, we'll update to the smallest preset that makes sense for the model. If you've chosen a preset that's bigger than the model, we keep it.
> feat(ollama): smarter preset selection based on models

- platform_umbrella/apps/control_server_web/lib/control_server_web/components/ollama/form_subcomponents.ex
We may want to do a quick look at the validations but this hides the count field unless a GPU is requested. :raised_hands:
> fix(ollama): only show gpu count if a gpu node type is selected

- platform_umbrella/apps/control_server_web/lib/control_server_web/components/postgres/postgres_backups_table.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/postgres/show.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/router.ex
- platform_umbrella/apps/kube_services/lib/kube_services/system_state/summary_backup.ex
Adds a table with the backups for a cluster to the cluster show page. This will be used for recovery in a future change.
> feat(postgres): display backups in UI

- platform_umbrella/apps/common_core/lib/mix/tasks/gen_resource.ex
Was getting errors. Not sure when they started but this change I've had stashed fixes 'em.
```bash
mix gen.resource <(helm template nfd https://github.com/kubernetes-sigs/node-feature-discovery/releases/download/v0.17.2/node-feature-discovery-chart-0.17.2.tgz) testing
** (ArgumentError) tried to unquote invalid AST: [%{"apiGroups" => [""], "resources" => ["namespaces"], "verbs" => ["watch", "list"]}, %{"apiGroups" => [""], "resources" => ["nodes", "nodes/status"], "verbs" => ["get", "patch", "update", "list"]}, %{"apiGroups" => ["nfd.k8s-sigs.io"], "resources" => ["nodefeatures", "nodefeaturerules", "nodefeaturegroups"], "verbs" => ["get", "list", "watch"]}, %{"apiGroups" => ["nfd.k8s-sigs.io"], "resources" => ["nodefeaturegroups/status"], "verbs" => ["patch", "update"]}, %{"apiGroups" => …
```
> chore(internal): fix resource generation

- platform_umbrella/apps/control_server/test/control_server/ferretdb_test.exs
- platform_umbrella/apps/control_server/test/control_server/knative_test.exs
- platform_umbrella/apps/control_server/test/control_server/metal_lb_test.exs
- platform_umbrella/apps/control_server/test/control_server/notebooks_test.exs
- platform_umbrella/apps/control_server/test/control_server/postgres_test.exs
- platform_umbrella/apps/control_server/test/control_server/projects/projects_test.exs
- platform_umbrella/apps/control_server/test/control_server/redis_test.exs
- platform_umbrella/apps/control_server/test/control_server/traditional_services/traditional_services_test.exs
- platform_umbrella/apps/control_server/test/support/data_case.ex
We're still getting some flakes on pagination tests. This doesn't rely on ordering or timing so should be reliable. Additionally, it excercises pagination more fully.
> chore: create better pagination test

- bin/bix
We used to have this with nix but it got dropped in the conversion but I find myself running `ex-test-deep` fairly regularly just to set up the DB.
> feat(bix): add ability to run test setup independently

- bootstrap/dev.install.json
- bootstrap/dev.spec.json
- bootstrap/int-prod.install.json
- bootstrap/int-prod.spec.json
- bootstrap/int-test.install.json
- bootstrap/int-test.spec.json
- bootstrap/jason.install.json
- bootstrap/jason.spec.json
- bootstrap/local.install.json
- bootstrap/local.spec.json
- bootstrap/team.json
- platform_umbrella/apps/common_core/lib/common_core/installs/traditional_services.ex
- platform_umbrella/apps/common_core/lib/common_core/state_summary/state_summary.ex
Looking at bootstrap stuff this morning and noticed we could pre-populate the `BATTERY_TEAM_IDS` instead of having to manually add it.
> fix(int-prod): bootstrap with team IDs pre-populated

- bin/common-functions.sh
Installs from home-base put the binaries in the same directory. `bix` cleans those up indiscriminately.
Put em in a subdir so `bix` only cleans up `bix` created binaries.
> fix(bix): place bi in subdirectory

- bi/pkg/installs/env.go
- bi/pkg/specs/get_spec.go
The algorithm changed but we didn't update it on the `bi` side which is preventing installations from installing.
> fix(bi): update signature algorithm to match new home-base

- platform_umbrella/apps/kube_bootstrap/lib/kube_bootstrap.ex
The production clusters have metrics/monitoring enabled. During bootstrap, we don't install the VM CRDs so the pod and service monitors never get created and bootstrapping fails.
> fix: allow bootstrapping a production cluster

- platform_umbrella/apps/kube_services/lib/kube_services/batteries/installed_watcher.ex
Summary:
- This should fix oauth enabled clusters
Test Plan:
- tried the repro locally and it passed
> fix: keep battery_core battery starting first no matter what

- platform_umbrella/config/prod.exs
- platform_umbrella/config/runtime.exs
Move the formatter configuration to runtime config. Moving to `new/1` should ensure that we always have a valid formatter config. I think the issue we had was that `redactors` was `nil` instead of `[]` which I fixed (temporarily) by copying the output of new to the compile time config.
> chore: refactor json logging configuration

- bin/bix
- platform_umbrella/apps/common_core/mix.exs
- platform_umbrella/apps/common_ui/mix.exs
- platform_umbrella/apps/control_server/mix.exs
- platform_umbrella/apps/control_server_web/mix.exs
- platform_umbrella/apps/event_center/mix.exs
- platform_umbrella/apps/home_base/mix.exs
- platform_umbrella/apps/home_base_web/mix.exs
- platform_umbrella/apps/kube_bootstrap/mix.exs
- platform_umbrella/apps/kube_services/mix.exs
- platform_umbrella/apps/verify/mix.exs
- platform_umbrella/mix.exs
Summary:
- bix set-version 0.66.0
Test Plan:
- Release after the bi version bump lands
> chore: prepare for 0.66.0 development

- .github/actions/setup-ci/action.yml
- .github/workflows/cache.yml
- platform_umbrella/apps/verify/lib/verify/kind_install_worker.ex
I think I've got integration tests working here in Actions so I'm breaking the change into smaller pieces.
This fixes (everything?) that #1869 did w/o adding the local bi binary to the cache.
Tangentially, it also changes the URL fetching from parsing it out of the output to getting it from the access-info configmap.
> ci: only build bi binary for int tests

- bootstrap/dev.install.json
- bootstrap/dev.spec.json
- bootstrap/int-prod.install.json
- bootstrap/int-prod.spec.json
- bootstrap/int-test.install.json
- bootstrap/int-test.spec.json
- bootstrap/jason.install.json
- bootstrap/jason.spec.json
- bootstrap/local.install.json
- bootstrap/local.spec.json
- bootstrap/team.json
- platform_umbrella/apps/common_core/lib/common_core/installs/postgres.ex
- platform_umbrella/apps/common_core/lib/common_core/installs/traditional_services.ex
The pg clusters for home_base and cla were preventing the cluster(s) from coming up in Actions runner. Remove 'em for now.
> chore(int-test): make the int test clusters smaller

- .github/workflows/int_test.yml
It took long enough that the containers eventually got published and pulled but we should just wait to start int-test until they are published.
https://github.com/batteries-included/batteries-included/actions/runs/14520777264/job/40740939744
> ci(int-test): wait until containers published

- bin/bix
The archiving step takes time and doesn't do much for us during CI. Skip it.
> bix: skip archiving when building bi

- platform_umbrella/apps/common_core/lib/common_core/notebooks/jupyter_lab_notebook.ex
- platform_umbrella/apps/common_core/lib/common_core/ollama/model_instance.ex
- platform_umbrella/apps/common_core/lib/common_core/util/virtual_size.ex
- platform_umbrella/apps/common_core/test/common_core/util/virtual_size_test.exs
Summary:
Add a module to get the matching virtual size for structs rather than
changesets
Test Plan:
- Tests included
> feat: add CommonCore.Util.VirtualSize

- platform_umbrella/config/prod.exs
- platform_umbrella/config/runtime.exs
Reverts batteries-included/batteries-included#1851
This change doesn't work with our releases without additional work.
> fix: revert refactor json logging configuration

- platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Summary:
- Preparing for a release
Test Plan:
- CI
> chore: bump stable bi version to 0.66.0

- bin/bix
- platform_umbrella/apps/common_core/mix.exs
- platform_umbrella/apps/common_ui/mix.exs
- platform_umbrella/apps/control_server/mix.exs
- platform_umbrella/apps/control_server_web/mix.exs
- platform_umbrella/apps/event_center/mix.exs
- platform_umbrella/apps/home_base/mix.exs
- platform_umbrella/apps/home_base_web/mix.exs
- platform_umbrella/apps/kube_bootstrap/mix.exs
- platform_umbrella/apps/kube_services/mix.exs
- platform_umbrella/apps/verify/mix.exs
- platform_umbrella/mix.exs
Summary:
- bix set-version
- This will land after the bi bump and the images are updated.
Test Plan:
- CI
- I'll cut a release assuming the verify is clean
> chore: prepare for 0.67.0

- .github/dependabot.yml
Summary:
Pastebin is one of the examples, so it doesn't need daily updates.
Test Plan:
- /shrug
> build: update pastbin deps less

- .github/dependabot.yml
Summary:
npm updates rarely do anything for us. So reduce the number that are
coming in. While it's not much it's not needed.
Test Plan:
- /shrug
> chore: slow dependabot for npm updates

- platform_umbrella/apps/control_server_web/lib/control_server_web/components/containers/containers_panel.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/k8/pod/show.ex
Summary:
In the browser any text that's in a pre tag can be selected by triple
clickinkg. It automatically makes sure that no added spaces are in the
selection. So this wraps the all the image names in that
Test Plan:
- Visual
- Tested copying
> fix: wrap image names in pre tag to allow copying

- bi/cmd/rage.go
- bi/cmd/start.go
- bi/cmd/stop.go
- bi/pkg/installs/env.go
- bi/pkg/kube/remove_all.go
- bi/pkg/rage/rage.go
- Only init when necessary to avoid removing kube config
- Allow rage to output to arbitrary location or stdout
> fix(bi): allow using `rage` during integration tests

- platform_umbrella/apps/kube_services/lib/kube_services/kube_state.ex
Noticed this as I was working. `table` spec is `atom() | tid()` so we can simplify here.
> chore(kube_services): simplify typespecs

- bootstrap/dev.install.json
- bootstrap/dev.spec.json
- bootstrap/int-prod.install.json
- bootstrap/int-prod.spec.json
- bootstrap/int-test.install.json
- bootstrap/int-test.spec.json
- bootstrap/jason.install.json
- bootstrap/jason.spec.json
- bootstrap/local.install.json
- bootstrap/local.spec.json
- bootstrap/team.json
We removed redis and ferretdb from int-test so re-gen without those.
> chore(bootstrap): re-gen specs to remove unused int-test batteries

- bi/cmd/aws/outputs.go
- bi/pkg/cluster/pulumi.go
- bi/pkg/installs/env.go
- bi/pkg/specs/battery_spec.go
- bi/pkg/specs/local_gateway.go
- bi/pkg/specs/print.go
- bi/pkg/specs/wait.go
- bi/pkg/specs/write_summary.go
pulumi will install the needed plugins without us needing to keep them in sync.
Address some other `TODO`s while I was in there.
> fix(bi): don't install unneeded plugins

- platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Summary:
- This bi version allows stopping
- Upgraded deps
Test Plan:
- CI
> chore: bump bi version

- platform_umbrella/apps/verify/test/postgres_test.exs
- platform_umbrella/apps/verify/test/redis_test.exs
- platform_umbrella/apps/verify/test/support/helpers.ex
I figured out why we were having issues with naming.
We auto-generate and re-set the names for e.g. postgres clusters on validation.
When wallaby clears and sets the value, it causes phoenix to reset the name in between clearing and setting. We can use set_value to send 100 backspaces and then the name we want and it works just fine!
This is needed to e.g. pick the postgres cluster for ferretdb.
> ci: fix random naming issue

- .github/workflows/bix.yml
- .github/workflows/bix_docker.yml
- .github/workflows/bix_elixir.yml
- .github/workflows/bix_go.yml
- .github/workflows/cache.yml
- .github/workflows/dependabot_automerge.yml
- .github/workflows/int_test.yml
- .github/workflows/release.yml
- .yamllint.yaml
Summary:
I read another report of github actions being compromised by poisoning a
repo and publishing a new version with an old tag. So this pins
everything. Since it has the comment, I think dependabot will still
update everthing
Test Plan:
CI
> build: pin actions to notics security issues

- bin/lib/common-functions.sh
I was focused on fixing the dangling port forward and missed that we're now killing ourselves and leaving a non-zero exit code.
```bash
zsh: terminated  bix m deps.get
 /batteries-included
❌143 ❯ bix m deps.get
```
> fix(bix): exit gracefully on cleanup

- platform_umbrella/apps/common_core/lib/common_core/defaults/images.ex
Description:
- 1.24.1 just dropped as a patch for the 1.x line. This updates to that
Test Plan:
- CI
- Tested locally
> chore: update ferretdb version

- bin/bi-source
- image_registry.yaml
- platform_umbrella/apps/common_core/lib/common_core/batteries/cert_manager_config.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/batteries/cert_manager_form.ex
The `cert_manager_ctl` image went away after 1.14.x and we haven't used it since then either.
> chore: remove unused cert manager image

- image_registry.yaml
- platform_umbrella/apps/common_core/lib/common_core/resources/istio/kiali_config_generator.ex
- platform_umbrella/apps/common_core/lib/common_core/resources/node_feature_discovery.ex
- platform_umbrella/apps/common_core/lib/common_core/resources/redis/redis_operator.ex
This makes all of our `imagePullPolicy`s and the registry consistent.
Will be helpful for image caching during integration testing.
> chore: ensure images are being pulled consistently

- platform_umbrella/apps/common_ui/lib/common_ui/components/script.ex
- platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/script_test/test_default_script_component.heyya_snap
- platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/script_test/test_script_with_custom_link.heyya_snap
- platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/script_test/test_script_with_template_component.heyya_snap
Description:
This should fix: #1849
Basically pre tags are copied without surroudning spaces by default in a web browser. So this PR changes to use pre tags rather than span.
Test Plan:
CI
> fix: use pre tags to allow copying with no extra spaces

- platform_umbrella/apps/common_ui/lib/common_ui/components/input.ex
- platform_umbrella/apps/common_ui/storybook/components/input/switch.story.exs
- platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/input_test/test_switch_input_component_disabled_with_boolean.heyya_snap
- platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/input_test/test_switch_input_component_with_boolean.heyya_snap
- platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/input_test/test_switch_input_component_with_error.heyya_snap
- platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/input_test/test_switch_input_component_with_label.heyya_snap
- platform_umbrella/apps/common_ui/test/common_ui/components/input_test.exs
Description:
using a label is what allows the embedded checkbox input be clickable. So this fixes switches
Test Plan:
Tests added and updated
Common UI/Visual
> fix: make switch properly get wrapped in label

- .github/actions/setup-ci/action.yml
- .github/workflows/int_test.yml
Now that we're caching the `bi` binary, we can get initial startup time of the integration tests to ~15 seconds.
That opens up the possibility of partitioning them across a few runners without wasting a ton of large runner time and money.
See: https://github.com/batteries-included/batteries-included/actions/runs/15116778489?pr=2014
> ci: partition int tests

- platform_umbrella/apps/verify/test/support/battery_install_worker.ex
This should fix the cert_manager failures on master. I'm not sure why we need to click the "Done" link but if fails without it and passes with it. /shrug
> fix(verify): wait for battery to be installed

- platform_umbrella/apps/verify/test/trivy_test.exs
We really are just asserting that a cluster RBAC audit has been completed. Doesn't matter which one so don't wait for a specific one.
> fix(verify): make trivy cluster RBAC test work

- .github/workflows/int_test.yml
If a partition fails, this won't fail the remaining partitions.
That makes for easier rerunning of failed partitions.
When we start testing against PRs, we'll probably want to change it.
> chore(ci): allow int test jobs to finish if other partition fails

- platform_umbrella/apps/control_server_web/lib/control_server_web/components/projects/import_snapshot_form.ex
Description:
Show the models that are being started on model import
Test Plan:
- Visual
> feat: display ollama model instances on import

- platform_umbrella/apps/verify/lib/verify/kind_install_worker.ex
- platform_umbrella/apps/verify/test/support/helpers.ex
If we don't have an updated summary, the deployment page may 404 and wallaby won't reload it.
I watched it happen locally with the istio csr test. I've been running just the cert_manager tests with this patch for 30 min already and haven't seen a failure yet. :crossed_fingers:
> fix(verify): robustify deployment checking

- registry-tool/cmd/advance_defaults.go
- registry-tool/cmd/flags.go
- registry-tool/cmd/list.go
- registry-tool/cmd/update_tags.go
- registry-tool/pkg/registry/registry_updater.go
Description:
Add list and a flad to filter to advancable images. This should help us script upgrading each image
Test Plan:
`go run registry-tool list ../image_registry.yaml -a` 
`go run registry-tool list ../image_registry.yaml -a -I ''` 
`go run registry-tool list ../image_registry.yaml`
> feat: add list command to registry-tool

- .github/dependabot.yml
Description:
Dependabot was complaining about our new time config: 
https://github.com/batteries-included/batteries-included/runs/43917758949
```
The property '#/updates/0/schedule/time' of type integer did not match the following type: string
The property '#/updates/1/schedule/time' of type integer did not match the following type: string
The property '#/updates/2/schedule/time' of type integer did not match the following type: string
The property '#/updates/3/schedule/time' of type integer did not match the following type: string
The property '#/updates/4/schedule/time' of type integer did not match the following type: string
The property '#/updates/5/schedule/time' of type integer did not match the following type: string
The property '#/updates/6/schedule/time' of type integer did not …
```
> fix: yaml parsing errors in dependabot

- platform_umbrella/apps/common_core/lib/common_core/projects/project_snapshot.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/projects/batteries_form.ex
Description:
On a new snapshot one of the options is to include a snapshot. When we do that we should make sure that the batteries are installed. 
Test Plan:
installed the open web ui project and it worked without needing to install batteries.
> feat: use imported snapshot to determine required batteries

- platform_umbrella/apps/control_server_web/lib/control_server_web/live/projects/show.ex
- platform_umbrella/apps/control_server_web/test/live/projects/show_pages_live_test.exs
Description:
Projects should be able to start ollama model instances from the show page. This adds a drop down link to do that. It follows the pattern of what's there before.
Test Plan:
- Tests added
- CI
> feat: add dropdown option to add model instance to a project

- platform_umbrella/apps/verify/test/support/battery_install_worker.ex
Description:
This changes from re-using the a single session to configure the battery, to using the returned session from fill_in_name
Test Plan:
will run on CI with label: int-test
> fix: maybe_add_config was flakey because it re-used session

- platform_umbrella/apps/common_core/lib/common_core/projects/project_snapshot.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/projects/import_snapshot_form.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/projects/new.ex
Description:
- Add an empty state for display when importing
- No batteries are required when there's nothing to import so change `ProjectSnapshot.required_batteries/1`
- Handle no import in the final step of the project form
Test Plan:
- Tested locally
> fix: allow not choosing a project to import

- bi/cmd/start_local.go
- bi/go.mod
- bi/go.sum
- bi/pkg/local/create.go
- bi/pkg/local/init.go
- platform_umbrella/apps/home_base/lib/home_base/customer_installs.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/controllers/installs/local_installation_controller.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/router.ex
Description:
- This adds the `start-local` command that will start a local installation with kind for development.
- This adds an api to create a new installation with those defaults
Test Plan:
- go run bi start-local --home-base started an install on my local machine.
> feat: allow starting a kind only cluster with bi

- platform_umbrella/apps/verify/test/support/helpers.ex
Description:
assert_workflow_pods_running does things that change the dom of the current session. We can't return stale sessions
Test Plan:
- CI
> fix(verify): return updated session in assert_workflow_pods_running

- .github/workflows/bix_docker.yml
Even though `cancel-in-progress` was false on master, it'd still cancel pending workflows (i.e. hadn't started yet) if a new workflow was triggered (e.g. from a merge to master).
This change limits it so that there's only a single concurrent run per commit which should prevent the many dependabot runs while leaving master unrestricted.
> ci: fix docker workflow concurrency

- platform_umbrella/apps/verify/lib/verify/image_pull_worker.ex
- platform_umbrella/apps/verify/test/keycloak_test.exs
- platform_umbrella/apps/verify/test/support/battery_install_worker.ex
- platform_umbrella/apps/verify/test/support/helpers.ex
- platform_umbrella/apps/verify/test/support/test_case.ex
- platform_umbrella/apps/verify/test/support/util.ex
We can start trying to pull images even before kind starts. Just keep retrying and as soon as the container is ready, it'll start pulling while we're still bootstrapping. Should save a lil bit off each test.
Additionally, update keycloak test to make sure we can log in.
> refactor(verify): pull images earlier and improve keycloak test

- bi/cmd/debug/list_local.go
- bi/pkg/installs/env.go
- bi/pkg/installs/list.go
- bi/pkg/installs/paths.go
- bi/pkg/installs/write.go
Description:
Add a debug command (debug because it's slighty a foot cannon) that will print all specs that are a local. This is useful for cleaning up, etc. However there are a lot of reasons the local FS can can out of sync with what other systems.
Test Plan:
- go run bi debug list-local
- remove spec files the listing went away
> feat: add bi debug list-local

- platform_umbrella/apps/verify/test/support/helpers.ex
- platform_umbrella/apps/verify/test/support/util.ex
Description:
Keycloak sso test is the last problem child. So this is an attempt to get the integration tests to pass on CI well. It first waits for keycloak's postgres cluster to be up. Then it starts waiting for the statefulset to be good. I also increased the max_wait_time so that waiting for the table row to appear can wait longer. For me I can't get this to fail on my machine any more. However CI was always the fun
Test Plan:
- Ran locally
- CI
> test: wait longer and earlier for keycloak

- .github/dependabot.yml
- .github/workflows/bix_docker.yml
Description:
Lots of PR's are having issues with canceled jobs that never complete. I think that's because we are canceling too many which is happening because we are triggering too many. This removes the 'on' triggers and canceling logic to try
Test Plan:
- CI
> build: try and stop double trigger/cancel

- platform_umbrella/apps/control_server_web/lib/control_server_web/live/k8/deployment/show.ex
- platform_umbrella/apps/control_server_web/lib/control_server_web/live/k8/stateful_set/show.ex
- platform_umbrella/apps/verify/test/forgejo_test.exs
- platform_umbrella/apps/verify/test/support/helpers.ex
- platform_umbrella/apps/verify/test/victoria_metrics_test.exs
> fix(verify): try to robustify keycloak tests once more

- .github/workflows/bix_registry.yml
- bin/bi-registry
- bin/bi-source
Description:
When the registry PR advances the default tag, its possible that we have changed one of the images that are used for bootstrapping. So whenever that's happened we should gen-static-specs
Test Plan:
/shrug
This created #2240 which includes a static spec regen. Everything in that PR looks good.
> feat: regenerate static specs on registry PR

- bi/go.mod
- bi/go.sum
- bi/pkg/cluster/kind/kind.go
- bi/pkg/cluster/kind/net.go
- bi/pkg/cluster/kind/net_test.go
- static/src/pages/copyrights.md
Offsets the metallb ip address pools based on the existing containers so that multiple clusters can be run simultaneously.
What other scenarios need testing?
> feat(bi): allow running multiple kind clusters

- bin/bi-source
- platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Description:
If the stable version of bi was the last release (somone hasn't needed to pin the version) then we should advance the stable bi version when setting a new version
Test Plan:
- Tried it locally.
> feat: bix s set-version should bump stable bi when possibl

- bi/pkg/cluster/pulumi.go
I got an error this morning because the version I had didn't match the go sdk version.
```
10:59:32.563 ERR cmd/root.go:39 Error executing command error="unable to start kube provider: error creating aws cluster: failed to refresh stack: failed to prepare refresh command: Pulumi CLI version >= 3.181.0 is required to use --client with refresh"
```
So let the automation API update the binary as needed.
> feat(bi): update pulumi version as needed

- platform_umbrella/apps/common_core/lib/common_core/actions/sso.ex
- platform_umbrella/apps/kube_services/lib/kube_services/snapshot_apply/apply_action.ex
The existing, built-in aliases aren't updated so e.g. in prod, the flow is still `Browser - Conditional OTP` and new installs would be `Browser - Conditional 2FA`.
Handle both conditions.
> fix(sso): handle upgraded installations with existing flow definitions

- platform_umbrella/apps/home_base_web/lib/home_base_web/live/dashboard_live.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/live/installation/show_live.ex
- platform_umbrella/apps/home_base_web/lib/home_base_web/router.ex
Description:
- Which recent install was on what team has been a pain. So this makes it even more clear.
- Restyle the show page to have a right menu
- Add a small usage page for the menu
Test Plan:
- Visual
> style: group by team for dashboard and restyle show page

- bin/bi-source
- platform_umbrella/apps/common_core/lib/common_core/ecto/enum.ex
- platform_umbrella/apps/common_core/lib/common_core/open_api/keycloak_admin_schema.ex
- platform_umbrella/apps/common_core/lib/common_core/port.ex
- platform_umbrella/apps/common_core/lib/common_core/protocol.ex
- platform_umbrella/apps/common_core/lib/common_core/resources/traditional_services/traditional_services.ex
- platform_umbrella/apps/common_core/lib/mix/tasks/gen_openapi_schema.ex
- platform_umbrella/apps/common_core/test/common_core/ecto/enum_test.exs
- platform_umbrella/apps/common_core/test/common_core/port_test.exs
- platform_umbrella/apps/common_core/test/common_core/protocol_test.exs
- platform_umbrella/apps/control_server_web/lib/control_server_web/components/port_modal.ex
Summary:
Keycloak now has an openapi schema. So this is the work needed to use
our existing code to regenerate with the latest
Test Plan:
Used it
> chore: regenerate openapi schema for keycloak

- platform_umbrella/apps/common_core/lib/common_core/ollama/model_instance.ex
Summary:
- Add both variants of gpt oss
- Move the cpu requirements for sizes down.
Test:
- model instances
> feat: add gpt-oss to the ollama models

- platform_umbrella/apps/common_core/lib/common_core/util/map.ex
- platform_umbrella/apps/common_core/test/common_core/util/map_utils_test.exs
By setting the `nvidia.com/gpu` limit to "0", karpenter was still assigning e.g. ollama to a GPU node. This changes the utility function to not put if the value or key is "0" or 0.
> fix(ml): don't allocate GPU nodes unnecessarily

- bi/pkg/start/start.go
Summary:
A while ago I checked and there were some intalls that were abandoned before they even reported once. I think that might be people trying it out and not knowing how long it takes. This change adds a log message that includes the expected time range for the installation, which can help users understand how long they might need to wait.
Test Plan:
- I started a local installation
> feat(start): enhance installation logging with expected time ranges

- platform_umbrella/apps/verify/test/home_base_test.exs
- platform_umbrella/apps/verify/test/support/helpers.ex
I'm not sure if I've seen it in GHA but I've seen quite a few failures locally where it doesn't navigate to the new installations page (stays on `/`). This seems to resolve it.
> fix(verify): robustify home base test some more

- .tool-versions
- bin/bi-docker
- bin/lib/docker-functions.sh
- docker/build-base.dockerfile
- docker/deploy-base.dockerfile
- image_registry.yaml
We keep track of versions and images in a few place but are consolidating to single repos/registries. This continues that work by moving base image version definitions to the registries.
> refactor(build): pull versions from existing registries

- bin/bi-registry
- registry-tool/cmd/root.go
- registry-tool/pkg/registry/error.go
- registry-tool/pkg/registry/registry_updater.go
Exit 1 from registry update jobs don't have an update. Exit > 1 for failures.
> ci: handle registry update job failures mo better

- bi/pkg/cluster/kind/kind.go
Summary:
- kind builds images, but you have no way of knowing if the node version
1.33.x is built for your version of kind library dependency. To get
around that they ask that you use sha verison for that
Test Plan:
- Use it locally
- int-test
> chore: update kindest image to one that's built for lib ver

- .github/workflows/bix_registry.yml
We generate static specs so having the elixir cache here is valuable.
> ci: do use elixir cache for registry update

- platform_umbrella/apps/control_server/lib/control_server/batteries/fixup.ex
- platform_umbrella/apps/kube_bootstrap/lib/kube_bootstrap.ex
- platform_umbrella/apps/kube_bootstrap/lib/kube_bootstrap/control_server.ex
- platform_umbrella/apps/kube_bootstrap/lib/kube_bootstrap/postgres.ex
- platform_umbrella/apps/verify/test/support/test_case.ex
Summary:
I've noticed some controlservers going into wait because the init fails.
That could slow things down. So try this
Test Plan:
- CI
- int-test
> fix(bootstrap): start controlserver after pg pod status.phase is running

- bi/pkg/installs/rage.go
- bi/pkg/kube/kube.go
- bi/pkg/kube/rage.go
- bi/pkg/rage/rage.go
Summary:
- Added functionality to gather and include node information in the rage report.
Test Plan:
- CI is failing everywhere so this will get run.
- I ran it locally and it had nodes in the report.
> feat: add node information to rage report

- platform_umbrella/apps/common_core/lib/common_core/installs/batteries.ex
It was "upgrading" mon-thurs to 1.4.0 something. I thought we did a version comparison to prevent downgrading there but that's not what I'm seeing.
> ci: fix home base test

- platform_umbrella/apps/control_server_web/mix.exs
- platform_umbrella/apps/home_base_web/mix.exs
- platform_umbrella/mix.exs
Dependabot updates for elixir [aren't working](https://github.com/batteries-included/batteries-included/actions/runs/17998106894/job/51201392803).
Due to:
phoenixframework/phoenix#6401
elixir-lang/elixir#14570
We'll be able to revert this after:
dependabot/dependabot-core#13143
> fix(deps): allow dependabot updates

- platform_umbrella/apps/kube_services/lib/kube_services/robo_sre/executors/delete_resource_executor.ex
- platform_umbrella/apps/kube_services/lib/kube_services/robo_sre/executors/restart_kube_state_executor.ex
- platform_umbrella/apps/kube_services/test/kube_services/robo_sre/executors/delete_resource_executor_test.exs
- platform_umbrella/apps/kube_services/test/kube_services/robo_sre/executors/restart_kube_state_executor_test.exs
- platform_umbrella/config/test.exs
Summary:
- Seems like there are other pids. I don't know how that could be
possible, but this changes it so that DeleteResourceExecutorTest
starts a process with a name and then uses the pid from then on.
- RestartKubeStateExecutorTest got the same treatment
- Both got some tests trimmed
- Changed the log levels for tests to get sanity back.
Test Plan:
- This is a test only PR
> test: attempt to make the robo sre tests not flakey on gh

- bin/bix-elixir
Summary:
- Flakey tests are taking too much time and it really looks like things
that are only test related now.
- Fix that by retrying
Test Plan:
- int-test on gh
> test: retry int-test one time to see if that stops flakey
