batteries-included/batteries-included

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
Set version to 0.19.0 for next version
I'll push a tag for the commit right before this
Test Plan:
CI
=> chore: release 0.18.1

bootstrap/damian.install.json, bootstrap/damian.spec.json, bootstrap/dev.install.json, bootstrap/dev.spec.json, bootstrap/elliott.install.json, bootstrap/elliott.spec.json, bootstrap/int-prod.install.json, bootstrap/int-prod.spec.json, bootstrap/int-test.install.json, bootstrap/int-test.spec.json, bootstrap/jason.install.json, bootstrap/jason.spec.json, bootstrap/local.install.json, bootstrap/local.spec.json, bootstrap/maurer.install.json, bootstrap/maurer.spec.json, bootstrap/team.json, platform_umbrella/apps/common_core/lib/common_core/defaults/images.ex
Summary:
1.23.2-distroless
Test Plan:
CI
=> chore: update istio patch version

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
set version to 0.20.0.
Test Plan:
CI
=> chore: prepare for 0.20.0 release

platform_umbrella/apps/common_ui/lib/common_ui/helpers/url_helpers.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/plug/sso_auth.ex, platform_umbrella/apps/home_base_web/lib/home_base_web/controllers/installation_script_controller.ex, platform_umbrella/apps/home_base_web/lib/home_base_web/live/installation/show_live.ex, platform_umbrella/apps/home_base_web/lib/home_base_web/request_host.ex
=> fix(home-base): clean up script and spec urls

platform_umbrella/apps/home_base_web/priv/raw_files/install_script.sh
=> fix(home): don't assume path

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
Since we should be ready for end to end. Bump the version
Test Plan:
End to end testing here we come.
=> chore: prepare for 0.21.0

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
`bix set-version 0.22.0`
Test Plan:
CI
=> chore: prepare for 0.22.0

platform_umbrella/apps/common_core/lib/common_core/et/urls.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/homes/magic.ex
=> fix(magic): use correct home base URLs

platform_umbrella/apps/common_core/lib/common_core/timeline/keycloak.ex, platform_umbrella/apps/common_core/lib/common_core/timeline/timeline_event.ex, platform_umbrella/apps/control_server/lib/control_server/timeline.ex, platform_umbrella/apps/control_server/test/control_server/timeline_test.exs, platform_umbrella/apps/control_server_web/lib/control_server_web/live/timeline.ex, platform_umbrella/apps/kube_services/lib/kube_services/keycloak/user_manager.ex, platform_umbrella/apps/kube_services/lib/kube_services/timeline.ex, platform_umbrella/apps/kube_services/lib/kube_services/timeline/keycloak.ex, platform_umbrella/apps/kube_services/lib/kube_services/timeline/keycloak_watcher.ex
=> feat(timeline): add keycloak user events

platform_umbrella/apps/common_ui/lib/common_ui/components/tooltip.ex, platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/tooltip_test/test_hover_tooltip_tooltip_render.heyya_snap, platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/tooltip_test/test_hover_tooltip_tooltip_with_class.heyya_snap, platform_umbrella/apps/common_ui/test/__snapshots__/common_ui/components/tooltip_test/test_truncate_tooltip_it_renders_with_long_strings.heyya_snap, platform_umbrella/apps/control_server_web/lib/control_server_web/live/timeline.ex
=> Fix timeline and hover tooltip in dark mode

platform_umbrella/apps/home_base_web/lib/home_base_web/live/installation/show_live.ex
=> feat(home-base): link to install's control server

bi/pkg/cluster/kind/kind.go, bi/pkg/cluster/pulumi.go
=> chore(bi): upgrade to k8s 1.31

platform_umbrella/apps/common_core/lib/common_core/et/namespace_report.ex, platform_umbrella/apps/home_base_web/lib/home_base_web/components/admin/usage_reports_table.ex, platform_umbrella/apps/home_base_web/lib/home_base_web/live/installation/show_live.ex
Summary:
The total pod count in one place
Test:
mix test
=> refactor: collapse down to on method for counting namespace report pod count

.goreleaser.yaml, bin/bix, bin/clean-tmp
Summary:
This should make goreleaser happy on small github
Test Plan:
Rebase some of the other changes on this.
=> chore: build releaster one at a time and clean between

platform_umbrella/apps/home_base_web/lib/home_base_web/live/installation/new_live.ex
Closes https://github.com/batteries-included/batteries-included/issues/883 by automatically selecting a default instance size based on the usage and provider. If the default size is manually changed, it will no longer automatically select one.
=> Auto choose a default instance size for new installations

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
Tag incoming for 0.22.0 final
We updated the emails and the home base installation and batteries. It
should be much better.
Test Plan:
Tags
=> chore: prepare for 0.23.0

README.md
Some changes to flesh out the README:
- Add logo (used email one without text because the other one didn't look good in a dark background)
- Re-organize a couple of things
- Add fedora/dnf instructions
- Fix typos/wording
- Add a few links
=> README lift

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
Quick release to see if you can tag non-dependabot commits.
Test Plan:
Tag github's it
=> chore: prepare for 0.24.0

static/src/pages/index.astro
Some ideas to get the ball rolling on the homepage.
=> Static site changes

static/src/pages/solutions/database.astro
Summary:
- Use the newly uploaded database video on the database page
- Change the database page to have a better ML section
Test Plan:
- Local testing
- netlify test deploy
=> feat: use the better video for database

bi/pkg/cluster/kind/net.go
=> fix(bi): don't give out more than a /24

platform_umbrella/apps/home_base_web/lib/home_base_web/live/dashboard_live.ex, platform_umbrella/apps/home_base_web/lib/home_base_web/live/installation/show_live.ex
Adds more invitations to create an installation, even if there are already existing installations.
---
=> Add more invitations to create an installation

bin/bix, platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
- Advance bi cli version. Preparing to use the latest version
- Advance the in master version
Test Plan:
- CI
=> chore: prepare for 0.25.0

static/src/components/widgets/StartBuild.astro, static/src/content/post/open-source-payoff.md, static/src/pages/landing/enable-your-devops-team-to-move-mountains.astro, static/src/pages/solutions/ai.astro, static/src/pages/solutions/database.astro, static/src/pages/solutions/security.astro, static/src/pages/solutions/sre_tools.astro, static/src/pages/solutions/web-deploy.astro
Summary:
This page doesn't exist
Test Plan:
git grep sign-up
=> docs: change dangling sign-up links

bin/bix, platform_umbrella/apps/home_base_web/lib/home_base_web/live/installation/new_live.ex, platform_umbrella/apps/home_base_web/priv/markdown/install/aws.md, platform_umbrella/apps/home_base_web/priv/markdown/install/kind.md, platform_umbrella/apps/home_base_web/priv/markdown/install/kind_kitchen_sink.md, platform_umbrella/apps/home_base_web/priv/markdown/install/kitchen_sink.md, platform_umbrella/apps/home_base_web/priv/markdown/install/provided.md
- What Kind installs do
- What Kitchen sink installs do
- What provided should do
- What AWS does
This PR also adds a formatting and tests for formatting of these markdown files.
=> docs: add installation how to's

static/src/data/navigation.ts
Summary:
Yes you can get support that way
Test Plan:
Netlify
=> docs: add github and slack as ways to get support

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
0.25.0 should be good to go
Test Plan:
Push 0.25 with the last docs changes and tag the things.
=> chore: prepare for 0.26.0

platform_umbrella/apps/common_core/lib/common_core/resources/istio/istio_ingress.ex
fixes: #1052 
This is just for traditional services for now but I should be able to add it for batteries in a follow up.
=> fix(traditional): redirect http to https if ssl enabled

platform_umbrella/apps/common_core/lib/common_core/resources/istio/istio_ingress.ex
=> fix(ssl): redirect http -> https

platform_umbrella/apps/home_base_web/priv/raw_files/install_script.sh
=> fix(homebase): turn down logging level in install script

bi/pkg/start/start.go
closes: #458 
This isn't my favorite but it should get the job done.
=> fix(bi): double check that bootstrap has completed

.github/workflows/bix_docker.yml, bin/bix
=> feat: tag images on release

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
We've done a lot lately. Time for a release
Test Plan:
CI
=> chore: prepare for 0.27.0

.github/workflows/bix_docker.yml
=> ci: fix container release/tag issues

.github/workflows/bix_docker.yml
=> ci: push images to ghcr

bi/pkg/specs/testdata/install_spec.json, bootstrap/damian.install.json, bootstrap/damian.spec.json, bootstrap/dev.install.json, bootstrap/dev.spec.json, bootstrap/elliott.install.json, bootstrap/elliott.spec.json, bootstrap/int-prod.install.json, bootstrap/int-prod.spec.json, bootstrap/int-test.install.json, bootstrap/int-test.spec.json, bootstrap/jason.install.json, bootstrap/jason.spec.json, bootstrap/local.install.json, bootstrap/local.spec.json, bootstrap/maurer.install.json, bootstrap/maurer.spec.json, bootstrap/team.json, platform_umbrella/apps/common_core/lib/common_core/defaults/images.ex, platform_umbrella/apps/common_core/test/common_core/state_summary/upgrade_test.exs, platform_umbrella/apps/common_core/test/support/factory.ex, platform_umbrella/apps/kube_services/lib/kube_services/batteries.ex
=> chore: migrate images to ghcr

.github/workflows/bix_docker.yml
=> ci: trigger docker image push/tag on tag

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
- Lets try
Test Plan:
- Your friendly neighborhood CI
=> chore: prepare 0.29.0

static/src/content/post/pgvector.md, static/src/pages/solutions/ai.astro
Summary:
as title
YAY
Test Plan:
netlify deploy
=> docs: use the new AI demo

platform_umbrella/apps/home_base_web/lib/home_base_web/live/login_live.ex, platform_umbrella/apps/home_base_web/lib/home_base_web/live/signup_live.ex
Moves the signup and login forms to the Fieldset component, and fixes the alignment on the TOS link as a result.
=> Fix signup form

platform_umbrella/apps/common_core/lib/common_core/resources/ferretdb.ex
closes: #1113 
We actually weren't giving the correct credentials for ferret to connect to postgres so I pulled in the enhancement to fix that issue.
=> fix(ferretdb): use pg secret for connection string

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
After fixes to security secrets, setup, and help pages it's time
Test Plan:
CI
=> chore: prepare for 0.30.0

platform_umbrella/apps/control_server_web/lib/control_server_web/components/containers/container_modal.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/components/containers/env_value_modal.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/components/knative/form_component.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/components/knative/form_subcomponents.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/components/port_modal.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/components/postgres/form_component.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/knative/edit.ex
=> Clean up Knative forms

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
New release
Test Plan:
CI
=> chore: prepare for 0.31.0

.github/workflows/bix_docker.yml
=> ci: quit pushing to ECR

platform_umbrella/apps/common_core/lib/common_core/resources/resource_generator.ex, platform_umbrella/apps/common_core/test/common_core/resources/resource_generator_test.exs
Summary:
Types and Test changes needed for it.
Test Plan:
CI
Tests updated after failing the new stricter guards
=> refactor: add type specs to resource generator

platform_umbrella/apps/control_server_web/lib/control_server_web/controllers/healthz_controller.ex, platform_umbrella/apps/kube_services/lib/kube_services/et/status_worker.ex
Summary:
Make sure that there is some install status that we get. Don't check
that it's good. We don't want the containers to flap
Test Plan:
CI
The on local
=> feat: check the install status worker on healthz

static/astro.config.mjs
Summary:
We can try other things when this stops timing out.
Test Plan:
Netlify doesn't time out.
=> fix: turn off image optimization for build speed

static/src/content/post/public-beta-announcement.md
Summary:
This should have been here
Test Plan:
netlify
=> fix: set publishDate for public beta announcement

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
Healthz works build a new release
Test Plan:
CI
=> chore: prepare 0.32.0

static/src/components/posts/List.astro, static/src/components/widgets/Content2.astro, static/src/components/widgets/Footer.astro, static/src/pages/[...blog]/[...page].astro, static/src/pages/[...blog]/[...slug].astro, static/src/pages/docs/[...page].astro, static/src/types.d.ts, static/src/utils/posts.ts, static/tsconfig.json
Summary:
General update on some code
Test Plan:
CI
=> chore: fix some typescript warnings on static

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
Prepare for a release after soft deletes went in.
Test Plan:
CI
=> chore: prepare for 0.33.0

platform_umbrella/apps/home_base_web/lib/home_base_web/live/help_live.ex
Summary:
I updated and wanted to check that it was updated before hitting delete.
However there wasn't a way. So I added this
Test Plan:
Visual
=> feat: add a version id to home base

platform_umbrella/apps/control_server_web/lib/control_server_web/components/containers/env_value_panel.ex
Summary:
Some times this will be sensitive
Test Plan:
CI
=> security: CommonUI.TextHelpers.obfuscate/2 the env value just in case

platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Summary:
Update the stable bi version to the latest release
Test Plan:
CI
=> chore: update stable bi version

platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Summary:
- Bump version now that the release is out
Test Plan:
- CI
=> chore: update bi stable version

bi/cmd/debug/kube_config_path.go
I am planning on using this for ensuring we're pointing at the correct cluster.
=> feat(bi): add debug command for getting kube config file

platform_umbrella/apps/control_server_web/lib/control_server_web/controllers/healthz_controller.ex, platform_umbrella/apps/kube_services/lib/kube_services/snapshot_apply/worker.ex
Summary:
in `/healthz` make sure that the worker gives some response back. This
makes sure the worker proccess is up and answering.
Test Plan:
`curl -vvv http://control.127-0-0-1.batrsinc.co:4000/healthz`
=> feat: make sure that KubeServices.SnapshotApply.Worker is alive

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
After the booting fixes and the health fixes lets release
Test Plan:
CI
=> chore: prepare for 0.35.0

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
Oauth fixes
Test Plan:
CI
=> chore: prepare 0.36.0

platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Summary:
bi 0.35.0 looks good
Test Plan:
CI
=> chore: bump stable bi to latest released

platform_umbrella/apps/control_server/test/support/factory.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/components/postgres/postgres_cluster_table.ex, platform_umbrella/apps/control_server_web/test/__snapshots__/components/postgres_table_test/test_postgres_clusters_table_abbridgred.heyya_snap, platform_umbrella/apps/control_server_web/test/__snapshots__/components/postgres_table_test/test_postgres_clusters_table_unabbridged.heyya_snap, platform_umbrella/apps/control_server_web/test/components/postgres_table_test.exs, platform_umbrella/apps/control_server_web/test/controllers/cluster_controller_test.exs
Summary:
This is based on user feedback. They wanted to know what type of
cluster, so they knew what to edit/what's safe.
Test Plan:
tests included
=> style: show pg cluster type on abbridged tables

platform_umbrella/apps/control_server_web/test/__snapshots__/components/postgres_table_test/test_postgres_clusters_table_abbridgred.heyya_snap, platform_umbrella/apps/control_server_web/test/components/postgres_table_test.exs
Summary:
I mis-spelled abridged.
Test Plan:
CI
=> fix: fix tests failing for control server web table

bi/pkg/cluster/kind/kind.go
Summary:
Kind node image update
Test Plan:
Start local
=> chore: update kind node image in bi

bootstrap/damian.install.json, bootstrap/damian.spec.json, bootstrap/dev.install.json, bootstrap/dev.spec.json, bootstrap/elliott.install.json, bootstrap/elliott.spec.json, bootstrap/int-prod.install.json, bootstrap/int-prod.spec.json, bootstrap/int-test.install.json, bootstrap/int-test.spec.json, bootstrap/jason.install.json, bootstrap/jason.spec.json, bootstrap/local.install.json, bootstrap/local.spec.json, bootstrap/maurer.install.json, bootstrap/maurer.spec.json, bootstrap/team.json, platform_umbrella/apps/common_core/lib/common_core/defaults/images.ex
Summary:
Update images for batteries that don't need crd or related updates
Test Plan:
- Started dev locally
- CI
- Started dev with redis, postgres, grafana, vm, etc
=> chore: update easy images

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
=> chore: prepare for 0.38.0

platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Summary:
Latest version released is 0.37.0 so bump to that
Test Plan:
Ci
=> chore: update stable version of bi

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
After keycloak is fixed.
Test Plan:
CI
=> chore: prepare for 0.39.0

platform_umbrella/apps/common_core/lib/common_core/resources/istio/istiod.ex
Summary:
istiod has a config from a json value file and a template. This pr
updates the json values to match latest versions and battery config
values
The -distroless tag being shared should make boot faster too.
Test Plan:
Ran locally
checked that 1.23.1-distroless was running
=> feat: update istio proxy tag on istiod

platform_umbrella/apps/common_core/lib/common_core/batteries/victoria_metrics_config.ex, platform_umbrella/apps/common_core/test/common_core/et/install_status_test.exs, platform_umbrella/apps/control_server_web/lib/control_server_web/components/batteries/victoria_metrics_form.ex
=> feat(monitoring): use sliders and presets for victoria metrics storage

platform_umbrella/apps/common_core/lib/common_core/traditional_services/service.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/components/traditional_services/form_subcomponents.ex
=> feat(traditional): allow custom sizing

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
Update to the next version
Test Plan:
CI
=> chore: prepare for 0.40.0

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
Getting ready to release 0.40.0 to use as the fresh install version.
Test Plan:
CI
=> chore: prepare for 0.41.0

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
- bix set version 42
Test Plan:
- CI
=> chore: prepare for the meaning of life

platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Summary:
- Bump version to the latest release
Test Plan:
- CI
=> chore: update the bi version to include s3 bucket

platform_umbrella/apps/common_core/lib/common_core/resources/postgres/cloudnative_pg_clusters.ex
This tells cnpg to add an annotation to each cluster's service account so that it will be able to assume the S3 role created in #1358 
part of: #1347
=> feat(cnpg): give cluster service accounts S3 permissions

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
Get a release with the fixed bi in it.
Test Plan:
CI
=> chore: prepare for 0.44.0

platform_umbrella/apps/common_core/lib/common_core/resources/postgres/cloudnative_pg_clusters.ex
part of: #1347 
This actually configures and starts backups from pg to S3.
=> feat(cnpg): enable barman backups to s3

platform_umbrella/apps/common_ui/lib/common_ui/components/link.ex, platform_umbrella/apps/control_server_web/assets/css/object_resource.css, platform_umbrella/apps/control_server_web/lib/control_server_web/components/object_display.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/k8/raw_resource.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/router.ex, platform_umbrella/apps/control_server_web/test/__snapshots__/components/raw_object_test/test_object_display__1_works_with_map_based_objects_deep_map.heyya_snap, platform_umbrella/apps/control_server_web/test/__snapshots__/components/raw_object_test/test_object_display__1_works_with_map_based_objects_deep_map_with_path.heyya_snap, platform_umbrella/apps/control_server_web/test/__snapshots__/components/raw_object_test/test_object_display__1_works_with_map_based_objects_easy_map.heyya_snap, platform_umbrella/apps/control_server_web/test/__snapshots__/components/raw_object_test/test_object_display__1_works_with_map_based_objects_easy_map_with_path.heyya_snap, platform_umbrella/apps/control_server_web/test/__snapshots__/components/raw_object_test/test_object_display__1_works_with_map_based_objects_map_with_array.heyya_snap, platform_umbrella/apps/control_server_web/test/__snapshots__/components/raw_object_test/test_object_display__1_works_with_map_based_objects_map_with_array_with_path.heyya_snap, platform_umbrella/apps/control_server_web/test/__snapshots__/components/raw_object_test/test_object_display__1_works_with_map_based_objects_map_with_array_with_selected.heyya_snap
Summary:
Style raw resource
Allow showing a resource with no namespace
Test Plan:
Used it
Visual
=> style: style the raw resouce links and make the page better

bootstrap/dev.install.json, bootstrap/dev.spec.json, bootstrap/int-prod.install.json, bootstrap/int-prod.spec.json, bootstrap/int-test.install.json, bootstrap/int-test.spec.json, bootstrap/jason.install.json, bootstrap/jason.spec.json, bootstrap/local.install.json, bootstrap/local.spec.json, bootstrap/team.json, platform_umbrella/apps/common_core/lib/common_core/installs/batteries.ex
Summary:
Make this not a complete and utter mess.
Test Plan:
CI still passes
=> refactor: clean up how we add to configs in install spec gen

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
- Getting ready to release 0.46.0
Test Plan:
- Ci
=> chore: prepare for 0.47.0

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
- Release with the bumped bi version
Test Plan:
- CI
=> chore: prepare for 0.48.0

platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Summary:
- Try and bump bi version
Test Plan:
- CI
=> chore: bump bi version

bootstrap/dev.install.json, bootstrap/dev.spec.json, bootstrap/int-prod.install.json, bootstrap/int-prod.spec.json, bootstrap/int-test.install.json, bootstrap/int-test.spec.json, bootstrap/jason.install.json, bootstrap/jason.spec.json, bootstrap/local.install.json, bootstrap/local.spec.json, bootstrap/team.json, platform_umbrella/apps/common_core/lib/common_core/installs/batteries.ex, platform_umbrella/apps/common_core/lib/common_core/installs/postgres.ex, platform_umbrella/apps/common_core/lib/common_core/installs/traditional_services.ex, platform_umbrella/apps/common_core/lib/common_core/state_summary/state_summary.ex
Sets up some of the stuff necessary for bootstrapping CLA assistant.
=> chore: easier bootstrapping of CLA assistant

static/src/content/post/devops-sre-learn.md, static/src/content/post/larger-llms-arent-all.md, static/src/content/post/openai-model-ver.md
Summary:
- Update sre post (This should go out soon)
- Update the llm's post (This desperately needs to go out it's already
old)
- Post the openai model version
Test Plan:
- CI
- netlify
=> docs: post content scrub

static/src/assets/images/logo-with-text-stacked.svg
Summary:
- NIT
Test Plan:
- None
=> chore: remove unsued path in svg

platform_umbrella/apps/common_core/lib/common_core/resources/istio/istio_configmap_generator.ex, platform_umbrella/apps/common_core/lib/common_core/state_summary/batteries.ex, platform_umbrella/apps/common_core/lib/common_core/state_summary/core.ex, platform_umbrella/apps/common_core/lib/common_core/state_summary/creds.ex, platform_umbrella/apps/common_core/lib/common_core/state_summary/namespaces.ex
Noticed this as I was working. Figured I'd get it throw it up separately.
=> refactor(core): better placement of battery fetching fn

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
- Set version
Test Plan:
- Release incoming
=> chore: prepare for 0.50.0

platform_umbrella/apps/common_core/lib/common_core/defaults/image.ex, platform_umbrella/apps/common_core/lib/common_core/defaults/images.ex, platform_umbrella/apps/common_core/lib/common_core/notebooks/jupyter_lab_notebook.ex
Summary:
Update to the new register
Test Plan:
- Started one
=> chore: upate jupyter notebook image

.github/workflows/release.yml, static/src/content/doc/running-release.md
Summary:
- Add a how to doc
- Make sure that we don't trigger gorelease on tags that aren't
release worthy (or sponge worthy).
Test Plan:
- CI
- netlify preview
=> chore: howto release

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
- Bump the version to start 0.54.0
Test Plan:
- CI
- Local testing
=> chore: prepare for 0.54.0

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
- Bump the version
Test Plan:
- CI
=> chore: prepare for 0.55.0

platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Summary:
- Preparing for another release
Test Plan:
- CI
=> chore: bump stable bi version

.goreleaser.yaml
Summary:
I forgot to put an order so it defaults to first. That's not where we
would want that section. Features should be first.
Test Plan:
- Next release
=> build: order chore section in releases

platform_umbrella/apps/common_core/lib/common_core/projects/project_snapshot.ex, platform_umbrella/apps/control_server/lib/control_server/projects/snapshotter.ex, platform_umbrella/apps/home_base/lib/home_base/et/stored_project_snapshot.ex
Summary:
- This isn't just for phoning back home.
Test Plan:
- CI
- `mix compile --force --warnings-as-errors`
=> refactor: project snapshot renaming

platform_umbrella/apps/control_server_web/lib/control_server_web/components/projects/projects_subcomponents.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/components/projects/recent_projects.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/components/redis/redis_table.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/ferrretdb/show.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/knative/show.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/notebooks/show.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/ollama/show.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/postgres/show.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/projects/edit.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/projects/export.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/projects/index.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/projects/new.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/projects/show.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/projects/timeline.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/redis/show.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/traditional_services/show.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/router.ex, platform_umbrella/apps/control_server_web/test/live/projects/project_live_test.exs, platform_umbrella/apps/control_server_web/test/live/projects/show_pages_live_test.exs
Summary:
This UI re-style follows the pattern other places, also it makes listing
and showing sub resources nice for larger projects
Test Plan:
- Tests included
=> style: Seperate pages for project show and make the main panel larger

platform_umbrella/apps/common_core/lib/common_core/batteries/knative_config.ex, platform_umbrella/apps/common_core/lib/common_core/knative/service.ex, platform_umbrella/apps/common_core/lib/common_core/resources/knative/services.ex, platform_umbrella/apps/common_core/lib/common_core/resources/secret.ex, platform_umbrella/apps/common_core/lib/common_core/resources/sso/oauth2_proxy.ex, platform_umbrella/apps/common_core/lib/common_core/resources/sso/proxy_utils.ex, platform_umbrella/apps/common_core/lib/common_core/state_summary/keycloak_summary.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/components/knative/form_component.ex
I still want to stress test this a bit in a variety of conditions.
Test plan:
=> feat(knative): add oauth2 proxy support

static/src/content/post/self-hosted-security.md
Summary:
The next release will have knative oauth. I think we are the only
platform with something like that. So we should start talking about
security before that.
Test Plan:
Netlify preview
=> docs: publish self hosting security post

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
Prep for release
Test Plan:
- CI
=> chore: prepare for 0.57.0

bin/bix, static/src/content/doc/getting-started.md
Summary:
We don't need an intro. They are here on the docs page.
Test Plan:
Netlify
=> docs: edit the getting started page

platform_umbrella/apps/common_core/lib/common_core/resources/ml/notebooks.ex
=> feat(notebooks): configure jupyter with overrides

bootstrap/dev.install.json, bootstrap/dev.spec.json, bootstrap/int-prod.install.json, bootstrap/int-prod.spec.json, bootstrap/int-test.install.json, bootstrap/int-test.spec.json, bootstrap/jason.install.json, bootstrap/jason.spec.json, bootstrap/local.install.json, bootstrap/local.spec.json, bootstrap/team.json, platform_umbrella/apps/common_core/lib/common_core/batteries/karpenter_config.ex, platform_umbrella/apps/common_core/lib/common_core/resources/karpenter.ex, platform_umbrella/apps/common_core/lib/common_core/resources/karpenter_pools.ex, platform_umbrella/apps/common_core/lib/common_core/resources/root.ex
This creates the nodepool resources. They aren't exposed anywhere but this is the first step in making GPUs available e.g. for ML.
=> chore(karpenter): create gpu specific nodepools

platform_umbrella/apps/common_core/lib/common_core/resources/battery/control_server.ex
I think everything running has the healthz endpoint by now so remove version check.
=> chore(control): remove temporary fix

bi/pkg/cluster/eks/cluster.go
The EBS CSI driver controller updated and needs new permissions. Instead of maintaining the policy ourselves, let Amazon handle updating the policy.
=> fix(bootstrap): use aws provided csi policy

bootstrap/dev.install.json, bootstrap/dev.spec.json, bootstrap/int-prod.install.json, bootstrap/int-prod.spec.json, bootstrap/int-test.install.json, bootstrap/int-test.spec.json, bootstrap/jason.install.json, bootstrap/jason.spec.json, bootstrap/local.install.json, bootstrap/local.spec.json, bootstrap/team.json
Summary:
New key type. New specs
Test Plan:
- bootstrap && dev
=> fix: re-generate the static specs

static/package-lock.json, static/src/assets/styles/tailwind.css, static/src/pages/pricing.astro
Summary:
- We don't have billing yet.
Test Plan:
- netlify
=> docs: chang the pricing page to say we are free

static/src/components/widgets/PricingCard.tsx, static/src/pages/pricing.astro
Made some improvements to the pricing page:
- Used bullet points for premium plan for visual consistency
- Slightly expanded feature lists/changed wording for clarity
- Added call-to-action with Slack link
- Changed wording to highlight the current free availability a bit more
=> Pricing page changes

platform_umbrella/apps/control_server/lib/control_server/projects/projects.ex, platform_umbrella/apps/control_server/lib/control_server/projects/snapshotter.ex, platform_umbrella/apps/control_server/test/control_server/projects/project_snapshot_test.exs, platform_umbrella/apps/control_server/test/support/factory.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/projects/show.ex
Summary:
- Ferretdb references a postgresql this should work
- includeded some ui tweaks on project snapshot pages
Test Plan:
Tests are include
=> feat: snapshots should work on ferretdb services

bin/bix
Summary:
This wasn't working for a lot of reasons.
Test Plan:
`bix build-static`
=> fix: bix static-build

docker/pastebin.dockerfile, docker/platform.dockerfile
Summary:
- Update erlang version
- Add apt clean after installing
Test Plan:
- CI
=> chore: update deps in docker build

platform_umbrella/apps/common_core/lib/common_core/batteries/catalog.ex, platform_umbrella/apps/common_core/lib/common_core/batteries/pg_restore_config.ex, platform_umbrella/apps/common_core/lib/common_core/batteries/system_battery.ex, platform_umbrella/apps/common_core/lib/common_core/postgres/cluster.ex, platform_umbrella/apps/common_core/lib/common_core/resources/postgres/cloudnative_pg_clusters.ex, platform_umbrella/apps/common_core/lib/common_core/resources/root.ex, platform_umbrella/apps/control_server/lib/control_server/projects/snapshotter.ex, platform_umbrella/apps/control_server/priv/repo/migrations/20250312194138_add_postgres_restore.exs, platform_umbrella/apps/control_server_web/lib/control_server_web/components/batteries/form_component.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/components/batteries/pg_restore_form.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/components/postgres/postgres_backups_table.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/postgres/show.ex
Backup recovery implemented behind the feature flagged `postgres_restore` battery.
=> feat(cnpg): restore from a postgres backup

bootstrap/dev.install.json, bootstrap/dev.spec.json, bootstrap/int-prod.install.json, bootstrap/int-prod.spec.json, bootstrap/int-test.install.json, bootstrap/int-test.spec.json, bootstrap/jason.install.json, bootstrap/jason.spec.json, bootstrap/local.install.json, bootstrap/local.spec.json, bootstrap/team.json, platform_umbrella/apps/common_core/lib/common_core/installs/postgres.ex, platform_umbrella/apps/common_core/lib/common_core/postgres/backup_config.ex, platform_umbrella/apps/common_core/lib/common_core/postgres/cluster.ex, platform_umbrella/apps/common_core/lib/common_core/resources/postgres/cloudnative_pg_clusters.ex, platform_umbrella/apps/control_server/priv/repo/migrations/20250312194138_add_postgres_restore.exs, platform_umbrella/apps/control_server_web/lib/control_server_web/components/postgres/form_component.ex, platform_umbrella/apps/kube_services/lib/kube_services/system_state/summary_batteries.ex
Allows configuring whether backups should be enabled or not. Does so in a way that is extensible as we expose additional backup configuration.
=> feat(cnpg): allow minimal backup configuration

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
Next release incoming
Test Plan:
- CI
=> chore: prepare for 0.58.0 release

platform_umbrella/rel/overlays/bin/make_admin
=> fix(home-base): use printf to quote make_admin command

bootstrap/dev.install.json, bootstrap/dev.spec.json, bootstrap/int-prod.install.json, bootstrap/int-prod.spec.json, bootstrap/int-test.install.json, bootstrap/int-test.spec.json, bootstrap/jason.install.json, bootstrap/jason.spec.json, bootstrap/local.install.json, bootstrap/local.spec.json, bootstrap/team.json, platform_umbrella/apps/common_core/lib/common_core/installs/postgres.ex
=> fix(int-prod): users need to be superusers

bootstrap/dev.install.json, bootstrap/dev.spec.json, bootstrap/int-prod.install.json, bootstrap/int-prod.spec.json, bootstrap/int-test.install.json, bootstrap/int-test.spec.json, bootstrap/jason.install.json, bootstrap/jason.spec.json, bootstrap/local.install.json, bootstrap/local.spec.json, bootstrap/team.json, platform_umbrella/apps/common_core/lib/common_core/resources/bootstrap/traditional_services.ex, platform_umbrella/apps/common_core/lib/common_core/resources/field_accessors.ex, platform_umbrella/apps/kube_services/lib/kube_services/stale/stale.ex
=> fix(int-prod): prevent seed data from being deleted too soon

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
The PR before this will be released asap
Test Plan:
- CI
=> chore: prepare for 0.59.0

platform_umbrella/apps/common_core/lib/common_core/resources/sso/keycloak.ex, platform_umbrella/apps/kube_bootstrap/lib/kube_bootstrap.ex
=> fix(bootstrap): only bootstrap what's needed for controlserver

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
- Release 0.59.0 to fix secure production
Test Plan:
- CI
=> chore: prepare for 0.60.0

platform_umbrella/apps/control_server_web/lib/control_server_web/live/knative/show.ex
Closes: #1799 if we don't care to add all of the URLs somewhere.
=> fix(knative): dont show link for internal service

platform_umbrella/apps/common_core/lib/common_core/installs/batteries.ex, platform_umbrella/apps/common_core/lib/common_core/state_summary/batteries.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/k8/pod/show.ex, platform_umbrella/apps/kube_services/lib/kube_services/system_state/summary_batteries.ex
=> fix(dashboards): don't show pod link if dashboard doesn't exist

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
- Release 0.60.0
Test Plan:
- CI
=> chore: prepare for 0.61.0

.github/actions/setup-ci/action.yml, .github/workflows/bix.yml, .github/workflows/bix_docker.yml, .github/workflows/bix_elixir.yml, .github/workflows/cache.yml
- Only run long cache jobs if they would be updated
- Don't pull large Go cache unless needed
=> ci: additional cleanup and speedups

platform_umbrella/apps/common_ui/assets/css/pagination.css, platform_umbrella/apps/common_ui/assets/css/shared.css
Summary:
This makes the style work agian.
Test Plan:
- Visual
=> style: add pagination-list and pagination-link styles

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
- Release new
Test Plan:
- None
=> chore: prepare for 0.63.0

platform_umbrella/apps/kube_services/lib/kube_services/snapshot_apply/keycloak.ex, platform_umbrella/apps/kube_services/lib/kube_services/snapshot_apply/worker.ex
Summary:
- Hopeing this fixes it for a little bit.
Test Plan:
- /shrug
=> fix: don't prepare/generate/apply keycloak before the process starts

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
- Next release
Test Plan:
- CI
=> chore: prepare for 0.64.0

platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Summary:
Another bump.
Test Plan:
- CI
=> core: bump bi stable version

platform_umbrella/config/prod.exs
Summary:
We don't run this on www. We run it on home
Though I don't think it's needed right now.
Test Plan:
- CI
=> fix: config should use the home host for prod

platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Summary:
- I'll make the release as soon as this lands
Test Plan:
- CI
=> chore: use 0.65.0 bi

bootstrap/dev.install.json, bootstrap/dev.spec.json, bootstrap/int-prod.install.json, bootstrap/int-prod.spec.json, bootstrap/int-test.install.json, bootstrap/int-test.spec.json, bootstrap/jason.install.json, bootstrap/jason.spec.json, bootstrap/local.install.json, bootstrap/local.spec.json, bootstrap/team.json, platform_umbrella/apps/common_core/lib/common_core/defaults/images.ex
Summary:
- This includes most of the images
- Still to come is victoria metrics operator and moving the default for
cloud native pg.
Test Plan:
- Started all the things on my local machine.
=> chore: update battery images

docker/build-base.dockerfile, docker/deploy-base.dockerfile, docker/platform.dockerfile
=> refactor(docker): slim down dependencies

.github/workflows/int_test.yml, platform_umbrella/apps/verify/lib/verify/kind_install_worker.ex, platform_umbrella/apps/verify/test/kube_test.exs, platform_umbrella/apps/verify/test/postgres_test.exs, platform_umbrella/apps/verify/test/project_creation_test.exs, platform_umbrella/apps/verify/test/redis_test.exs, platform_umbrella/apps/verify/test/support/test_case.ex
=> ci(int-test): capture rage and screenshots on failure

platform_umbrella/apps/common_core/lib/common_core/installs/batteries.ex, platform_umbrella/apps/verify/lib/verify/application.ex, platform_umbrella/apps/verify/test/kube_test.exs, platform_umbrella/apps/verify/test/postgres_test.exs, platform_umbrella/apps/verify/test/project_creation_test.exs, platform_umbrella/apps/verify/test/redis_test.exs, platform_umbrella/apps/verify/test/support/battery_install_worker.ex, platform_umbrella/apps/verify/test/support/helpers.ex, platform_umbrella/apps/verify/test/support/test_case.ex
- adds BatteryInstallWorker to install batteries necessary for a test module
- removes unnecessary batteries from bootstrapping for `int-test`
- refactors test helpers
=> feat(verify): add ability to install batteries

.github/actionlint.yaml
I have actionlint setup us as an automatic linter. This adds a basic config so that it works well here.
=> chore: set up actionlint config

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
Bump version
Test Plan:
CI
=> chore: prepare for 0.68.0 development

platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Summary:
- Version bump
Test Plan:
- CI
=> chore: bump bi to version 0.68.0

bin/bix, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
Niiiice
Test Plan:
CI
=> chore: prepare for 0.69.0 development

platform_umbrella/apps/verify/test/ferretdb_test.exs
=> feat(verify): add initial ferretdb tests

.github/workflows/int_test.yml, platform_umbrella/apps/verify/test/ferretdb_test.exs, platform_umbrella/apps/verify/test/knative_test.exs, platform_umbrella/apps/verify/test/postgres_test.exs, platform_umbrella/apps/verify/test/redis_test.exs, platform_umbrella/apps/verify/test/support/helpers.ex
=> feat(verify): add initial knative test

bin/bi-elixir, bin/bi-local, bin/bix, bin/lib/common-functions.sh, bin/pg-forward
It seems like the commit before the refactor had the same (or similar) issue where I could get dangling port forwards. Not sure why. But this has fixed it for me.
=> fix(bix): don't leave dangling port forwards

platform_umbrella/apps/verify/test/support/helpers.ex, platform_umbrella/apps/verify/test/traditional_test.exs
=> feat(verify): initial traditional service test

platform_umbrella/.credo.exs, platform_umbrella/apps/common_core/lib/common_core/accounts/user.ex, platform_umbrella/apps/common_core/lib/common_core/open_api/lago.ex, platform_umbrella/apps/common_core/lib/common_core/resources/ml/notebooks.ex, platform_umbrella/apps/common_core/lib/common_core/version.ex, platform_umbrella/apps/common_core/lib/mix/tasks/gen_resource.ex, platform_umbrella/apps/common_core/test/common_core/jwk/jwk_test.exs, platform_umbrella/apps/common_core/test/common_core/resources/istio/kiali_config_generator_test.exs, platform_umbrella/apps/common_core/test/common_core_test.exs, platform_umbrella/apps/common_ui/lib/common_ui/components/table.ex, platform_umbrella/apps/control_server/lib/control_server/projects/snapshotter.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/state_summary.ex, platform_umbrella/apps/kube_bootstrap/.formatter.exs, platform_umbrella/apps/kube_bootstrap/config/runtime.exs, platform_umbrella/apps/kube_bootstrap/lib/kube_bootstrap.ex, platform_umbrella/apps/kube_bootstrap/lib/kube_bootstrap/kube.ex, platform_umbrella/apps/kube_bootstrap/lib/kube_bootstrap/postgres.ex, platform_umbrella/apps/kube_bootstrap/lib/kube_bootstrap/tasks.ex, platform_umbrella/apps/kube_bootstrap/lib/mix/tasks/kube_bootstrap.ex, platform_umbrella/apps/kube_bootstrap/test/kube_bootstrap_test.exs, platform_umbrella/apps/kube_services/lib/kube_services/keycloak/admin_client.ex, platform_umbrella/apps/kube_services/lib/kube_services/keycloak/user_manager.ex, platform_umbrella/apps/kube_services/lib/kube_services/snapshot_apply/event_launcher.ex, platform_umbrella/apps/kube_services/lib/kube_services/timeline/battery_watcher.ex, platform_umbrella/config/dev.exs
Description:
- Update the .credo.exs
- Update a lot of the found nits
- This is mostly to re-enable dbg testing
Test Plan:
- CI still passes
=> style: update .credo.exs

bin/bi-local
Description:
Add a bix command that ties all the local source together to test the local git commit
Test Plan:
- Running it locally currently
=> test: add `bix local int-test`

platform_umbrella/apps/home_base/lib/home_base/projects/static_projects.ex, platform_umbrella/apps/home_base/priv/stored_projects/batt_019741bce3157609b800f611baa82b9a.json
Description:
- Add Serverless Example
Test Plan:
- CI
=> feat: add serverless example project

platform_umbrella/apps/home_base/lib/home_base/projects/static_projects.ex, platform_umbrella/apps/home_base/priv/stored_projects/batt_019745dfea447de6ae4b47b7bb7834e4.json
Description:
Knative is a beast sometimes. So offer an example that doesn't use it.
Test Plan:
Import shows it.
=> feat: add new traditional example project

registry-tool/pkg/registry/registry_updater.go
Description:
- Changed wasn't being set to true anymore. This PR fixes that.
Test Plan:
- Used it
=> fix: registry too change detection for writing was broken

bootstrap/dev.install.json, bootstrap/dev.spec.json, bootstrap/int-prod.install.json, bootstrap/int-prod.spec.json, bootstrap/int-test.install.json, bootstrap/int-test.spec.json, bootstrap/jason.install.json, bootstrap/jason.spec.json, bootstrap/local.install.json, bootstrap/local.spec.json, bootstrap/team.json, image_registry.yaml, registry-tool/cmd/advance_defaults.go, registry-tool/pkg/registry/image_record.go, registry-tool/pkg/registry/image_record_test.go, registry-tool/pkg/versions/compare.go, registry-tool/pkg/versions/sort_test.go
Update all the things. What could go wrong?
=> chore(deps): update all images in the registry and advance defaults

.github/workflows/bix_docker.yml
I have no idea what the problem was but this fixes it.
=> ci: fix artifact id passing

platform_umbrella/apps/verify/test/forgejo_test.exs
Remove flakes while the battery config gets figured out.
=> chore(verify): remove battery config temporarily

platform_umbrella/apps/verify/test/forgejo_test.exs, platform_umbrella/apps/verify/test/support/battery_install_worker.ex
=> fix(verify): de-flake battery install

image_registry.yaml
Description:
Advance the default for ollama and pg
Test Plan:
- CI
=> chore: bump image defaults

image_registry.yaml, platform_umbrella/apps/common_core/lib/common_core/batteries/trivy_operator_config.ex, platform_umbrella/apps/common_core/lib/common_core/batteries/victoria_metrics_config.ex, platform_umbrella/apps/common_core/lib/common_core/batteries/vm_agent_config.ex, platform_umbrella/apps/common_core/lib/common_core/defaults/images.ex, platform_umbrella/apps/common_core/lib/common_core/resources/trivy_operator.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/components/batteries/trivy_operator_form.ex, platform_umbrella/apps/verify/lib/verify/image_pull_worker.ex, platform_umbrella/apps/verify/test/kiali_test.exs, platform_umbrella/apps/verify/test/kube_monitoring_test.exs, platform_umbrella/apps/verify/test/trivy_test.exs, platform_umbrella/apps/verify/test/victoria_metrics_test.exs
=> fix: migrate remaining images to registry

registry-tool/pkg/registry/registry.go
Description:
- Closer to what prettier will give us
Test Plan:
- CI
=> feat: fix registry-tools yaml indent

image_registry.yaml, platform_umbrella/apps/common_core/lib/common_core/batteries/istio_csr_config.ex, platform_umbrella/apps/common_core/lib/common_core/resources/istio/istio_csr.ex, platform_umbrella/apps/verify/test/cert_manager_test.exs, registry-tool/cmd/flags.go
missed this guy
part of: #2131
=> fix: migrate istio csr to registry

bin/bi-registry
Description:
Follow the pattern
Test Plan:
- /shrug
=> refactor: better title for bi-registry-bot commits

bin/lib/common-functions.sh, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Description:
Prepare for 0.71.0 development
Release incoming
Test Plan:
- CI
=> chore: prepare for 0.71.0

.github/workflows/bix_registry.yml
Description:
Setup is failing so trying to simplify
Test Plan:
I'll trigger it.
=> fix: try and fix bix registry update

.github/workflows/bix_registry.yml, bin/bi-registry
Description:
I Changed battieries included cla bot's name to batteries included bot. Then I added a secret to be used in this repo.
Hooked this up here
Test Plan:
- Trigger incoming
=> build: use REGISTRY_BOT_PAT for registrybot

static/src/pages/index.astro
Description:
We moved AI up to this version, so include that in this page
Test Plan:
- CI
- Netlify
=> docs: add more AI info to the home page of static

bootstrap/dev.install.json, bootstrap/dev.spec.json, bootstrap/int-prod.install.json, bootstrap/int-prod.spec.json, bootstrap/int-test.install.json, bootstrap/int-test.spec.json, bootstrap/jason.install.json, bootstrap/jason.spec.json, bootstrap/local.install.json, bootstrap/local.spec.json, bootstrap/team.json
We had some version upgrades that needed to be reflected in the static specs.
=> chore: re-gen static specs

bin/lib/common-functions.sh, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Description:
- Bump version to release the new oauth fixes
Test Plan:
- CI
=> chore: prepare for 0.72.0 development

platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Description:
The config fix is worth a release
Test Plan:
- CI
=> chore: bump stable bi version to upcoming 0.72.0

platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex
Description:
- Version bump incoming
Test Plan:
- ci
=> chore: bump stable bi

static/src/content/post/devops-sre-learn.md
Description:
- More content to push out
Test Plan:
- Netlify
=> docs: publish devops-sre

image_registry.yaml, platform_umbrella/apps/common_core/lib/common_core/actions/battery_core.ex, platform_umbrella/apps/verify/test/sso_test.exs, platform_umbrella/apps/verify/test/support/helpers.ex
Description:
For the batteries included realm use the new shiny realm
Test Plan:
- used it locally.
=> feat: use the bi-keycloak-theme for BI realm

image_registry.yaml
=> chore(karpenter): upgrade

platform_umbrella/apps/control_server_web/assets/js/app.ts, platform_umbrella/apps/control_server_web/assets/js/object-display.ts, platform_umbrella/apps/control_server_web/lib/control_server_web/components/object_display.ex, platform_umbrella/apps/control_server_web/test/__snapshots__/components/raw_object_test/test_object_display__1_works_with_map_based_objects_deep_map.heyya_snap, platform_umbrella/apps/control_server_web/test/__snapshots__/components/raw_object_test/test_object_display__1_works_with_map_based_objects_deep_map_with_path.heyya_snap, platform_umbrella/apps/control_server_web/test/__snapshots__/components/raw_object_test/test_object_display__1_works_with_map_based_objects_easy_map.heyya_snap, platform_umbrella/apps/control_server_web/test/__snapshots__/components/raw_object_test/test_object_display__1_works_with_map_based_objects_easy_map_with_path.heyya_snap, platform_umbrella/apps/control_server_web/test/__snapshots__/components/raw_object_test/test_object_display__1_works_with_map_based_objects_map_with_array.heyya_snap, platform_umbrella/apps/control_server_web/test/__snapshots__/components/raw_object_test/test_object_display__1_works_with_map_based_objects_map_with_array_with_path.heyya_snap, platform_umbrella/apps/control_server_web/test/__snapshots__/components/raw_object_test/test_object_display__1_works_with_map_based_objects_map_with_array_with_selected.heyya_snap
Summary:
This adds a new hook that will scroll the new column into view. It makes the object display much nicer to use.
Test:
- Verified locally with the kubernetes pods.
=> feat: add ObjectDisplayHook and integrate with object display component

platform_umbrella/apps/control_server_web/lib/control_server_web/live/k8/deployment/show.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/live/k8/stateful_set/show.ex, platform_umbrella/apps/control_server_web/lib/control_server_web/router.ex, platform_umbrella/apps/control_server_web/test/live/k8/deployment_live_test.exs, platform_umbrella/apps/control_server_web/test/live/k8/stateful_set_live_test.exs
Description:
- Continue to use the same style for statefulset and deployment
- Update the router
Test Plan:
- Visual
=> style: use right menu for statefulset and deployment

platform_umbrella/apps/common_core/lib/common_core/resources/sso/proxy_utils.ex, platform_umbrella/apps/verify/test/sso_test.exs, platform_umbrella/apps/verify/test/support/helpers.ex
A quick follow up will remove smtp4dev from the rest of the codebase.
=> fix(verify): migrate sso oauth2 proxy test to victoria metrics

bin/lib/common-functions.sh, keycloak-theme/vite.config.ts, platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
- Prepare for the post 1.0.0 development
Test Plan:
- RELEASE INCOMING
=> chore: prepare for 1.0.1 development

bi/pkg/specs/wait.go
The wg connection doesn't work for publicly accessible clusters so bootstrapping fails in AWS. Only use the wg connection to check the control server if it's local.
Test plan:
=> fix(bi): only use wireguard for http client locally

bin/bi-keycloak, bin/lib/common-functions.sh, keycloak-theme/vite.config.ts, platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
- Hot fix that mother
Test Plan:
- CI
=> chore: prepare for 1.0.2

platform_umbrella/apps/control_server_web/lib/control_server_web/live/postgres/show.ex
Watch for new backups on the cluster show page.
=> feat(cnpg): watch for new cluster backups

bin/lib/common-functions.sh, keycloak-theme/vite.config.ts, platform_umbrella/apps/common_core/lib/common_core/defaults/versions.ex, platform_umbrella/apps/common_core/mix.exs, platform_umbrella/apps/common_ui/mix.exs, platform_umbrella/apps/control_server/mix.exs, platform_umbrella/apps/control_server_web/mix.exs, platform_umbrella/apps/event_center/mix.exs, platform_umbrella/apps/home_base/mix.exs, platform_umbrella/apps/home_base_web/mix.exs, platform_umbrella/apps/kube_bootstrap/mix.exs, platform_umbrella/apps/kube_services/mix.exs, platform_umbrella/apps/verify/mix.exs, platform_umbrella/mix.exs
Summary:
- bix s set-version 1.2.0
Test Plan:
- ci
=> chore: prepare for 1.2.0 development

bin/bi-keycloak
Summary:
I thought this was running and I was seeing it through TRACE=1 echoing.
Test Plan:
- I can't break this worse
=> fix(build): keycloak was echoing the correct thing

bin/bi-docker, docker/build-base.dockerfile, docker/deploy-base.dockerfile, docker/keycloak.dockerfile, docker/pastebin.dockerfile, docker/platform.dockerfile
Summary:
LABEL all the things, but no license since we don't have spx
Test Plan:
- build
=> build: add oci labels to images

bootstrap/dev.install.json, bootstrap/dev.spec.json, bootstrap/int-prod.install.json, bootstrap/int-prod.spec.json, bootstrap/int-test.install.json, bootstrap/int-test.spec.json, bootstrap/jason.install.json, bootstrap/jason.spec.json, bootstrap/local.install.json, bootstrap/local.spec.json, bootstrap/team.json, image_registry.yaml
This is an automated update of the image registry.
Changes:
- Update image tags
- Advance default tags
=> chore(deps): Automated registry update [bi-registry-bot]

bootstrap/dev.install.json, bootstrap/dev.spec.json, bootstrap/int-prod.install.json, bootstrap/int-prod.spec.json, bootstrap/int-test.install.json, bootstrap/int-test.spec.json, bootstrap/jason.install.json, bootstrap/jason.spec.json, bootstrap/local.install.json, bootstrap/local.spec.json, bootstrap/team.json, image_registry.yaml
Test plan:
new cluster: :white_check_mark:
existing cluster (upgrade): :white_check_mark:
=> chore: update AWS image tags

platform_umbrella/apps/home_base/lib/home_base/seed.ex
Summary:
I want to be able to test from master to branch with new bootstrap. This
was the thing stopping me.
Test:
Will try it.
=> refactor: don't fail home base seed

image_registry.yaml, platform_umbrella/apps/common_core/lib/common_core/resources/ferretdb.ex, registry-tool/cmd/flags.go
This works end-to-end with a dump from 1 and restore to 2.5.0.
=> feat!: upgrade to ferretdb 2.0+

bi/pkg/kube/rage.go, bi/pkg/rage/rage.go
Summary:
- Add event for pods events
- Fill that out
Test Plan:
- `go run . rage dev`
- CI on this pr
=> feat: add events to pods in rage

platform_umbrella/apps/kube_services/lib/kube_services/kube_state/resource_watcher.ex
Summary:
I left in a field by mistake. I was trying to use just one field for the
current retry time. However there was still one place referencing the
old field. That meant that we never grew the base retry time for and
watchers. We hammered the api server on starup.
Test:
- Code review
- Starts everything here
=> fix: don't hammer the api server on not-found

static/src/assets/styles/tailwind.css
Summary:
- V4 tailwind has a new method that I didn't carry over
Test Plan:
- Visual
=> docs: fix prose plugin not affecting css

bin/bix-elixir
Summary:
Did you know that if returns 0 as its return value? I didn't then. I do
now.
Test Plan:
Running this locally until trivvy fails.
=> test: fix retry on int-test
